/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Views_panels;
//Importaciones de generales para el facil acceso a metodos y atributos:

import java.awt.Color;
import DataBase_Models.Usuarios;
import Interfaces.*;
import View.*;
import javax.swing.JOptionPane;

/**
 *
 * @author Fabrizio
 */
public class AdicionesUsuarios extends javax.swing.JPanel {

    //Variables de uso global del programa:
    boolean isEdition = false;
    Usuarios usuarioEdition;

    /**
     * Creates new form prinicipal
     */
    public AdicionesUsuarios() {
        initComponents();
        //Metodo insertor de imagen:
        //ImageIcon();
        //Estilos del panel:
        InitStylesPanel();
    }

    //Constructor parametrizado para la reutilizacion del titulo del panel 
    //y sus componentes.
    public AdicionesUsuarios(Usuarios usuario) {
        initComponents();
        //Declaracion de la variable usuarioEdition:
        usuarioEdition = usuario;
        isEdition = true;
        InitStylesPanel();
    }

    //Metodo para los JTextField
    //CONDICION: METODO FALLIDO:
    /*
    private void handlePlaceholder(JTextField field, String placeholder) {
        if (field.getText().equals(placeholder)) {
            field.setText("");
            field.setForeground(Color.black);
        }
        if (field.getText().isEmpty()) {
            field.setText(placeholder);
            field.setForeground(Color.gray);
        }
    }
     */
    //Estilos para el panel DEVOLUCIONES:
    private void InitStylesPanel() {
        //Encabezado de titulo:
        lblTitle_RegistroUsuarioPanel.putClientProperty("FlatLaf.styleClass", "h1");

        //Mas metodos ha incluir(Opcional).
        //Generador de leyendas para los campos de captura de texto:
        txtFldNombre_RegistroUsuarioPanel.putClientProperty("JTextField.placeholderText", "Ingrese su nombre(s)");
        txtFldApellidoPaterno_RegistroUsuarioPanel.putClientProperty("JTextField.placeholderText", "Ingrese su apellido paterno");
        txtFldApellidoMaterno_RegistroUsuarioPanel.putClientProperty("JTextField.placeholderText", "Ingrese su apellido materno");
        txtFldDomicilio_RegistroUsuarioPanel.putClientProperty("JTextField.placeholderText", "Ingrese la direccion de su domicilio");
        txtFldTelefono_RegistroUsuarioPanel.putClientProperty("JTextField.placeholderText", "Ingrese su numero telefonico");

        //Cambio de panel intuitivo: REGISTRO -> EDICION 
        if (isEdition) {
            //Cambio del titulo del label original: REGISTRO -> EDICION
            lblTitle_RegistroUsuarioPanel.setText("EDITAR USUARIO");
            //Cambio del titulo del buttom original: REGISTRAR -> GUARDAR
            btnRegistrar_RegistroUsuarioPanel.setText("GUARDAR");
            //Comprobacion de que el campo de texto no sea nulo:
            if (usuarioEdition != null) {
                //Campos de captura de texto:
                txtFldNombre_RegistroUsuarioPanel.setText(usuarioEdition.getName());
                txtFldApellidoPaterno_RegistroUsuarioPanel.setText(usuarioEdition.getLast_name_p());
                txtFldApellidoMaterno_RegistroUsuarioPanel.setText(usuarioEdition.getLast_name_m());
                txtFldDomicilio_RegistroUsuarioPanel.setText(usuarioEdition.getDomicilio());
                txtFldTelefono_RegistroUsuarioPanel.setText(usuarioEdition.getTel());
            }
        } else {
            //Cambio de titulo tras la secuencia condicional:
            lblTitle_RegistroUsuarioPanel.setText("REGISTRO DE USUARIOS");
        }
    }

    //Metodo de imagen:
    //Al ser un panel refactor del otro, copia todo su codigo
    //NOTA: No afecta en mucho si es que esta bien codificado.
    //      metodo fallido de insercion de imagen:
    //private void ImageIcon() {
    //CONDICION: Metodo fallido:
    /*        
        URL imageURL = getClass().getResource("/Images/EBSCO-LISTA-344x258-c-default.jpg");
        if (imageURL != null) {
            Icon mIcon = new ImageIcon(new ImageIcon("/Images/EBSCO-LISTA-344x258-c-default.jpg").getImage().getScaledInstance(lblimageIcon.getWidth(), lblimageIcon.getHeight(), Image.SCALE_SMOOTH));
            lblimageIcon.setIcon(mIcon);  // Asegura que el ícono se establezca en el JLabel
        } else {
            System.out.println("Image not found!");
        }
     */
    //Solucion:
    //Insercion deesde icons por URL externa.
    //}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlBackground_RegistroUsuarioPanel = new javax.swing.JPanel();
        lblTitle_RegistroUsuarioPanel = new javax.swing.JLabel();
        lblNombres_RegistroUsuarioPanel = new javax.swing.JLabel();
        txtFldNombre_RegistroUsuarioPanel = new javax.swing.JTextField();
        jSeparator2_RegistroUsuarioPanel = new javax.swing.JSeparator();
        lblApellidoPaterno_RegistroUsuarioPanel = new javax.swing.JLabel();
        txtFldApellidoPaterno_RegistroUsuarioPanel = new javax.swing.JTextField();
        jSeparator3_RegistroUsuarioPanel = new javax.swing.JSeparator();
        lblApellidoMaterno_RegistroUsuarioPanel = new javax.swing.JLabel();
        txtFldApellidoMaterno_RegistroUsuarioPanel = new javax.swing.JTextField();
        jSeparator4_RegistroUsuarioPanel = new javax.swing.JSeparator();
        lblDomicilio_RegistroUsuarioPanel = new javax.swing.JLabel();
        txtFldDomicilio_RegistroUsuarioPanel = new javax.swing.JTextField();
        jSeparator1_RegistroUsuarioPanel = new javax.swing.JSeparator();
        lblTelefono_RegistroUsuarioPanel = new javax.swing.JLabel();
        txtFldTelefono_RegistroUsuarioPanel = new javax.swing.JTextField();
        jSeparator5_RegistroUsuarioPanel = new javax.swing.JSeparator();
        btnRegistrar_RegistroUsuarioPanel = new javax.swing.JButton();
        lblimage_RegistroUsuarioPanel = new javax.swing.JLabel();

        pnlBackground_RegistroUsuarioPanel.setBackground(new java.awt.Color(255, 255, 255));
        pnlBackground_RegistroUsuarioPanel.setMinimumSize(new java.awt.Dimension(0, 0));
        pnlBackground_RegistroUsuarioPanel.setPreferredSize(new java.awt.Dimension(0, 0));

        lblTitle_RegistroUsuarioPanel.setForeground(new java.awt.Color(0, 0, 0));
        lblTitle_RegistroUsuarioPanel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitle_RegistroUsuarioPanel.setText("REGISTRO DE USUARIOS");

        lblNombres_RegistroUsuarioPanel.setForeground(new java.awt.Color(0, 0, 0));
        lblNombres_RegistroUsuarioPanel.setText("NOMBRE(S)");

        jSeparator2_RegistroUsuarioPanel.setForeground(new java.awt.Color(204, 204, 204));

        lblApellidoPaterno_RegistroUsuarioPanel.setForeground(new java.awt.Color(0, 0, 0));
        lblApellidoPaterno_RegistroUsuarioPanel.setText("APELLIDO PATERNO");

        jSeparator3_RegistroUsuarioPanel.setForeground(new java.awt.Color(204, 204, 204));

        lblApellidoMaterno_RegistroUsuarioPanel.setBackground(new java.awt.Color(0, 0, 0));
        lblApellidoMaterno_RegistroUsuarioPanel.setForeground(new java.awt.Color(0, 0, 0));
        lblApellidoMaterno_RegistroUsuarioPanel.setText("APELLIDO MATERNO");

        jSeparator4_RegistroUsuarioPanel.setForeground(new java.awt.Color(204, 204, 204));

        lblDomicilio_RegistroUsuarioPanel.setBackground(new java.awt.Color(0, 0, 0));
        lblDomicilio_RegistroUsuarioPanel.setForeground(new java.awt.Color(0, 0, 0));
        lblDomicilio_RegistroUsuarioPanel.setText("DOMICILIO");

        jSeparator1_RegistroUsuarioPanel.setForeground(new java.awt.Color(204, 204, 204));
        jSeparator1_RegistroUsuarioPanel.setOrientation(javax.swing.SwingConstants.VERTICAL);

        lblTelefono_RegistroUsuarioPanel.setBackground(new java.awt.Color(0, 0, 0));
        lblTelefono_RegistroUsuarioPanel.setForeground(new java.awt.Color(0, 0, 0));
        lblTelefono_RegistroUsuarioPanel.setText("TELEFONO");

        jSeparator5_RegistroUsuarioPanel.setForeground(new java.awt.Color(204, 204, 204));

        btnRegistrar_RegistroUsuarioPanel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnRegistrar_RegistroUsuarioPanel.setText("REGISTRAR");
        btnRegistrar_RegistroUsuarioPanel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnRegistrar_RegistroUsuarioPanel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrar_RegistroUsuarioPanelActionPerformed(evt);
            }
        });

        lblimage_RegistroUsuarioPanel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblimage_RegistroUsuarioPanel.setIcon(new javax.swing.ImageIcon("C:\\Users\\Fabrizio\\OneDrive\\Documentos\\ToGit - NetBeans\\LibraryManagement_System\\Program_Images\\images.jpg")); // NOI18N

        javax.swing.GroupLayout pnlBackground_RegistroUsuarioPanelLayout = new javax.swing.GroupLayout(pnlBackground_RegistroUsuarioPanel);
        pnlBackground_RegistroUsuarioPanel.setLayout(pnlBackground_RegistroUsuarioPanelLayout);
        pnlBackground_RegistroUsuarioPanelLayout.setHorizontalGroup(
            pnlBackground_RegistroUsuarioPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlBackground_RegistroUsuarioPanelLayout.createSequentialGroup()
                .addContainerGap(49, Short.MAX_VALUE)
                .addGroup(pnlBackground_RegistroUsuarioPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jSeparator4_RegistroUsuarioPanel, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblApellidoMaterno_RegistroUsuarioPanel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jSeparator3_RegistroUsuarioPanel, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblApellidoPaterno_RegistroUsuarioPanel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblNombres_RegistroUsuarioPanel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTitle_RegistroUsuarioPanel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
                    .addComponent(jSeparator2_RegistroUsuarioPanel, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblDomicilio_RegistroUsuarioPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtFldNombre_RegistroUsuarioPanel)
                    .addComponent(txtFldApellidoPaterno_RegistroUsuarioPanel)
                    .addComponent(txtFldApellidoMaterno_RegistroUsuarioPanel)
                    .addComponent(txtFldDomicilio_RegistroUsuarioPanel))
                .addGap(66, 66, 66)
                .addComponent(jSeparator1_RegistroUsuarioPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(pnlBackground_RegistroUsuarioPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlBackground_RegistroUsuarioPanelLayout.createSequentialGroup()
                        .addGap(106, 106, 106)
                        .addComponent(btnRegistrar_RegistroUsuarioPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlBackground_RegistroUsuarioPanelLayout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addGroup(pnlBackground_RegistroUsuarioPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblTelefono_RegistroUsuarioPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jSeparator5_RegistroUsuarioPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
                            .addGroup(pnlBackground_RegistroUsuarioPanelLayout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(lblimage_RegistroUsuarioPanel))
                            .addComponent(txtFldTelefono_RegistroUsuarioPanel))))
                .addGap(42, 42, 42))
        );
        pnlBackground_RegistroUsuarioPanelLayout.setVerticalGroup(
            pnlBackground_RegistroUsuarioPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBackground_RegistroUsuarioPanelLayout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(pnlBackground_RegistroUsuarioPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(pnlBackground_RegistroUsuarioPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jSeparator1_RegistroUsuarioPanel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 338, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnlBackground_RegistroUsuarioPanelLayout.createSequentialGroup()
                            .addComponent(lblTitle_RegistroUsuarioPanel)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(lblNombres_RegistroUsuarioPanel)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(txtFldNombre_RegistroUsuarioPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jSeparator2_RegistroUsuarioPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(lblApellidoPaterno_RegistroUsuarioPanel)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(txtFldApellidoPaterno_RegistroUsuarioPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jSeparator3_RegistroUsuarioPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(lblApellidoMaterno_RegistroUsuarioPanel)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(txtFldApellidoMaterno_RegistroUsuarioPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jSeparator4_RegistroUsuarioPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(lblDomicilio_RegistroUsuarioPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(txtFldDomicilio_RegistroUsuarioPanel)))
                    .addGroup(pnlBackground_RegistroUsuarioPanelLayout.createSequentialGroup()
                        .addComponent(lblTelefono_RegistroUsuarioPanel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtFldTelefono_RegistroUsuarioPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator5_RegistroUsuarioPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnRegistrar_RegistroUsuarioPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lblimage_RegistroUsuarioPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(53, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlBackground_RegistroUsuarioPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 801, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlBackground_RegistroUsuarioPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 430, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegistrar_RegistroUsuarioPanelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrar_RegistroUsuarioPanelActionPerformed
        //Instanciacion de los JTextFields correspondientes:
        String nombre = txtFldNombre_RegistroUsuarioPanel.getText();
        String apellidoPaterno = txtFldApellidoPaterno_RegistroUsuarioPanel.getText();
        String apellidoMaterno = txtFldApellidoMaterno_RegistroUsuarioPanel.getText();
        String domicilio = txtFldDomicilio_RegistroUsuarioPanel.getText();
        String telefono = txtFldTelefono_RegistroUsuarioPanel.getText();

        //Validadciones para los campos de entrada de texto:
        if (nombre.equals("Ingrese su nombre(s)") || apellidoPaterno.equals("Ingrese su apellido paterno")
                || apellidoMaterno.equals("Ingrese su apellido materno") || domicilio.equals("Ingrese la direccion de su domicilio")
                || telefono.equals("Ingrese su numero telefonico")) {
            JOptionPane.showMessageDialog(null, "Por favor, asegurese de que todos los campos estan completos, Gracias.", "iBooking", JOptionPane.WARNING_MESSAGE);
            //Redireccion el cursor al cuadro de texto "txtFldNombre_RegistroUsuarioPanel"
            txtFldNombre_RegistroUsuarioPanel.requestFocus();
            return;
        }

        //Adicion de la informacion capturada en los campos instanciados:
        //PROCESO: Si se trata de una edicion, se asigna automaticamente un nuevo usuario o lo que traiga en "usuarioEdition"
        //         caso contrario que si no se encuentra, se cree un nuvo obejto de tipo "Usuarios()".           
        Usuarios usuario = isEdition ? usuarioEdition : new Usuarios();
        usuario.setName(nombre);
        usuario.setLast_name_p(apellidoPaterno);
        usuario.setLast_name_m(apellidoMaterno);
        usuario.setDomicilio(domicilio);
        usuario.setTel(telefono);

        //Uso del "try{...} catch (Exception e) {...}" para localizar posibles errores de compilacion.
        try {
            DAOUsuarios dao = new DAOUsuariosImpl();

            //Validador de regristro y modificacion:
            if (!isEdition) {
                //Crea un nuevo objeto usuarioID():
                dao.Registrar(usuario);
            } else {
                //Captura un ID de usuario:
                dao.Modificar(usuario);
            }

            //Confirmador de exito de operacion:
            String successMessage = isEdition ? "modificado" : "registrado";
            //Anuncio pop-up de confirmacion de la operacion:
            //NOTA: Se aprecia que se utiliza el objeto de tipo String superior, para variar el mensaje segun sea el caso aplicativo.
            JOptionPane.showMessageDialog(null, "Usuario " + successMessage + " exitosamente :) ", "iBooking", JOptionPane.INFORMATION_MESSAGE);

            //Condicional usada para NO borrar automaticamente todos los campos de texto capturado previamente:
            if (!isEdition) {
                //Metodo de reestablecimiento de leyendas automaticamente tras transaccion exitosa:
                //Campo: Nombre
                txtFldNombre_RegistroUsuarioPanel.setText("Ingrese su nombre(s)");
                txtFldNombre_RegistroUsuarioPanel.setForeground(Color.gray);
                //Campo: Apellido Paterno
                txtFldApellidoPaterno_RegistroUsuarioPanel.setText("Ingrese su apellido paterno");
                txtFldApellidoPaterno_RegistroUsuarioPanel.setForeground(Color.gray);
                //Campo: Apellido Materno
                txtFldApellidoMaterno_RegistroUsuarioPanel.setText("Ingrese su apellido materno");
                txtFldApellidoMaterno_RegistroUsuarioPanel.setForeground(Color.gray);
                //Campo: Domicilio
                txtFldDomicilio_RegistroUsuarioPanel.setText("Ingrese la direccion de su domicilio");
                txtFldDomicilio_RegistroUsuarioPanel.setForeground(Color.gray);
                //Campo: Telefono
                txtFldTelefono_RegistroUsuarioPanel.setText("Ingrese su numero telefonico");
                txtFldTelefono_RegistroUsuarioPanel.setForeground(Color.gray);
                //CHECKPOINT: Sabado 11/01/2025 - 15:56
            }
        } catch (Exception e) {
            //Mensaje de error en base al caso propuesto:
            String errorMessage = isEdition ? "modificar" : "registrar";
            //NOTA: Se aprecia el uso del objeto de tipo String, el cual modifica el mensaje segun sea la operacion,
            //      se puede apreciar el mismo caso en el bloque superior de condicion exitosa.
            JOptionPane.showMessageDialog(null, "Ohps! Ocurrio un error al " + errorMessage + " el usuario. :(", "iBooking", JOptionPane.ERROR_MESSAGE);
            System.out.println(e.getMessage());
        }
    }//GEN-LAST:event_btnRegistrar_RegistroUsuarioPanelActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRegistrar_RegistroUsuarioPanel;
    private javax.swing.JSeparator jSeparator1_RegistroUsuarioPanel;
    private javax.swing.JSeparator jSeparator2_RegistroUsuarioPanel;
    private javax.swing.JSeparator jSeparator3_RegistroUsuarioPanel;
    private javax.swing.JSeparator jSeparator4_RegistroUsuarioPanel;
    private javax.swing.JSeparator jSeparator5_RegistroUsuarioPanel;
    private javax.swing.JLabel lblApellidoMaterno_RegistroUsuarioPanel;
    private javax.swing.JLabel lblApellidoPaterno_RegistroUsuarioPanel;
    private javax.swing.JLabel lblDomicilio_RegistroUsuarioPanel;
    private javax.swing.JLabel lblNombres_RegistroUsuarioPanel;
    private javax.swing.JLabel lblTelefono_RegistroUsuarioPanel;
    private javax.swing.JLabel lblTitle_RegistroUsuarioPanel;
    private javax.swing.JLabel lblimage_RegistroUsuarioPanel;
    private javax.swing.JPanel pnlBackground_RegistroUsuarioPanel;
    private javax.swing.JTextField txtFldApellidoMaterno_RegistroUsuarioPanel;
    private javax.swing.JTextField txtFldApellidoPaterno_RegistroUsuarioPanel;
    private javax.swing.JTextField txtFldDomicilio_RegistroUsuarioPanel;
    private javax.swing.JTextField txtFldNombre_RegistroUsuarioPanel;
    private javax.swing.JTextField txtFldTelefono_RegistroUsuarioPanel;
    // End of variables declaration//GEN-END:variables
}
