/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Views_panels;
//Importaciones de generales para el facil acceso a metodos y atributos:

import java.awt.Color;
//CHECKPOINT: Domingo, 09/02/2025 - 
//NOTA: Implementacion de funcionalidades para la seccion "Devoluciones.java"
import DataBase_Models.*;
import Interfaces.*;
import Utilities.*;
import View.*;
import java.util.Date;
import javax.swing.JOptionPane;

/**
 *
 * @author Fabrizio
 */
public class Devoluciones extends javax.swing.JPanel {

    //Variables de uso global:
    private final int dia_max_devolucion = 5;
    private final int sancion_costo_por_dia = 10;

    /**
     * Creates new form prinicipal
     */
    public Devoluciones() {
        initComponents();
        //Metodo insertor de imagen:
        //ImageIcon();
        //Estilos del panel:
        InitStylesPanel();
    }

    //Estilos para el panel DEVOLUCIONES:
    private void InitStylesPanel() {
        lblTitle_DevolucionPanel.putClientProperty("FlatLaf.styleClass", "h1");
        //Mas metodos ha incluir(Opcional).
        //Generador de leyenda en las cajas de captura de texto:
        txtFldUsuario_DevolucionPanel.putClientProperty("JTextField.placeholderText", "Ingrese el foilo de usuario");
        txtFldLibroID_DevolucionPanel.putClientProperty("JTextField.placeholderText", "Ingrese el ID del libro a devolver");
    }

    //Metodo de imagen:
    //Al ser un panel refactor del otro, copia todo su codigo
    //NOTA: No afecta en mucho si es que esta bien codificado.
    //metodo fallido de insercion de imagen:
    //private void ImageIcon() {
        //Metodo fallido:
        /*        
        URL imageURL = getClass().getResource("/Images/EBSCO-LISTA-344x258-c-default.jpg");
        if (imageURL != null) {
            Icon mIcon = new ImageIcon(new ImageIcon("/Images/EBSCO-LISTA-344x258-c-default.jpg").getImage().getScaledInstance(lblimageIcon.getWidth(), lblimageIcon.getHeight(), Image.SCALE_SMOOTH));
            lblimageIcon.setIcon(mIcon);  // Asegura que el ícono se establezca en el JLabel
        } else {
            System.out.println("Image not found!");
        }
         */
        //Solucion:
        //Insercion deesde icons por URL externa.
    //}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlBackground_DevolucionPanel = new javax.swing.JPanel();
        lblTitle_DevolucionPanel = new javax.swing.JLabel();
        lblFolioUsuario_DevolucionPanel = new javax.swing.JLabel();
        txtFldUsuario_DevolucionPanel = new javax.swing.JTextField();
        jSeparator2_DevolucionPanel = new javax.swing.JSeparator();
        lblLibroID_DevolucionPanel = new javax.swing.JLabel();
        txtFldLibroID_DevolucionPanel = new javax.swing.JTextField();
        jSeparator3_DevolucionPanel = new javax.swing.JSeparator();
        btnDevolver_DevolucionPanel = new javax.swing.JButton();
        jSeparator1_DevolucionPanel = new javax.swing.JSeparator();
        lblimagen_DevolucionPanel = new javax.swing.JLabel();

        pnlBackground_DevolucionPanel.setBackground(new java.awt.Color(255, 255, 255));
        pnlBackground_DevolucionPanel.setMinimumSize(new java.awt.Dimension(0, 0));
        pnlBackground_DevolucionPanel.setPreferredSize(new java.awt.Dimension(0, 0));

        lblTitle_DevolucionPanel.setForeground(new java.awt.Color(0, 0, 0));
        lblTitle_DevolucionPanel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitle_DevolucionPanel.setText("DEVOLUCION DE LIBRO");

        lblFolioUsuario_DevolucionPanel.setForeground(new java.awt.Color(0, 0, 0));
        lblFolioUsuario_DevolucionPanel.setText("FOLIO DE USUARIO:");

        jSeparator2_DevolucionPanel.setForeground(new java.awt.Color(204, 204, 204));

        lblLibroID_DevolucionPanel.setForeground(new java.awt.Color(0, 0, 0));
        lblLibroID_DevolucionPanel.setText("LIBRO ID:");

        jSeparator3_DevolucionPanel.setForeground(new java.awt.Color(204, 204, 204));

        btnDevolver_DevolucionPanel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnDevolver_DevolucionPanel.setText("DEVOLVER");
        btnDevolver_DevolucionPanel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnDevolver_DevolucionPanel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDevolver_DevolucionPanelActionPerformed(evt);
            }
        });

        jSeparator1_DevolucionPanel.setForeground(new java.awt.Color(204, 204, 204));
        jSeparator1_DevolucionPanel.setOrientation(javax.swing.SwingConstants.VERTICAL);

        lblimagen_DevolucionPanel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblimagen_DevolucionPanel.setIcon(new javax.swing.ImageIcon("C:\\Users\\Fabrizio\\OneDrive\\Documentos\\ToGit - NetBeans\\LibraryManagement_System\\Program_Images\\istockphoto-1335708681-612x612.jpg")); // NOI18N

        javax.swing.GroupLayout pnlBackground_DevolucionPanelLayout = new javax.swing.GroupLayout(pnlBackground_DevolucionPanel);
        pnlBackground_DevolucionPanel.setLayout(pnlBackground_DevolucionPanelLayout);
        pnlBackground_DevolucionPanelLayout.setHorizontalGroup(
            pnlBackground_DevolucionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlBackground_DevolucionPanelLayout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(pnlBackground_DevolucionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblTitle_DevolucionPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 292, Short.MAX_VALUE)
                    .addComponent(lblFolioUsuario_DevolucionPanel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jSeparator2_DevolucionPanel, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblLibroID_DevolucionPanel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jSeparator3_DevolucionPanel, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnDevolver_DevolucionPanel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtFldUsuario_DevolucionPanel)
                    .addComponent(txtFldLibroID_DevolucionPanel))
                .addGap(28, 28, 28)
                .addComponent(jSeparator1_DevolucionPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 10, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(lblimagen_DevolucionPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 382, Short.MAX_VALUE)
                .addGap(24, 24, 24))
        );
        pnlBackground_DevolucionPanelLayout.setVerticalGroup(
            pnlBackground_DevolucionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBackground_DevolucionPanelLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(pnlBackground_DevolucionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jSeparator1_DevolucionPanel, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblimagen_DevolucionPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(36, 36, 36))
            .addGroup(pnlBackground_DevolucionPanelLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(lblTitle_DevolucionPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblFolioUsuario_DevolucionPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtFldUsuario_DevolucionPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2_DevolucionPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblLibroID_DevolucionPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtFldLibroID_DevolucionPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator3_DevolucionPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 18, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnDevolver_DevolucionPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(88, 88, 88))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlBackground_DevolucionPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 800, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlBackground_DevolucionPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 430, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnDevolver_DevolucionPanelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDevolver_DevolucionPanelActionPerformed
        //Inicializacion de variables:
        //String de conuslta en la base de datos:
        String folioUsuario = txtFldUsuario_DevolucionPanel.getText();
        String libroID = txtFldLibroID_DevolucionPanel.getText();

        //Validaciones de campos de entrada de texto:
        if (folioUsuario.isEmpty() || libroID.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Debe completar todos los campos de texto.", "iBooking", JOptionPane.ERROR_MESSAGE);
            txtFldUsuario_DevolucionPanel.requestFocus();
            return;
        } else if (!Utilidades.isNumeric(folioUsuario) || !Utilidades.isNumeric(libroID)) {
            JOptionPane.showMessageDialog(null, "Los campos de texto Folio y el ID deben ser numeros interos.", "iBooking", JOptionPane.ERROR_MESSAGE);
            txtFldUsuario_DevolucionPanel.requestFocus();
            return;
        } else if (Integer.parseInt(folioUsuario) <= 0 || Integer.parseInt(libroID) <= 0) {
            JOptionPane.showMessageDialog(null, "Los campos de texto Folio y el ID deben ser mayor que 0 para cada campo.", "iBooking", JOptionPane.ERROR_MESSAGE);
            txtFldUsuario_DevolucionPanel.requestFocus();
            return;
        }

        try {
            //Validacion de existencia de usuario en los campos:
            DAOUsuarios daoUsuarios = new DAOUsuariosImpl();
            DataBase_Models.Usuarios usuarioActual = daoUsuarios.getUsuarioByID(Integer.parseInt(folioUsuario));
            if (usuarioActual == null) {
                JOptionPane.showMessageDialog(null, "No se encontro ningun usuario con ese folio.", "iBooking", JOptionPane.ERROR_MESSAGE);
                txtFldUsuario_DevolucionPanel.requestFocus();
                return;
            }
            //Validacion de existencia de libros en los campos:
            DAOLibros daoLibros = new DAOLibrosImp();
            DataBase_Models.Libros libroActual = daoLibros.getLibrobyID(Integer.parseInt(libroID));
            if (libroActual == null) {
                JOptionPane.showMessageDialog(null, "No se encontro ningun libro con ese ID.", "iBooking", JOptionPane.ERROR_MESSAGE);
                txtFldUsuario_DevolucionPanel.requestFocus();
                return;
            }
            //Validacion de existencia de prestamos en los campos:
            DAOPrestamos daoPrestamos = new DAOPrestamosImp();
            DataBase_Models.Prestamos prestamoActual = daoPrestamos.getPrestamos(usuarioActual, libroActual);
            if (prestamoActual == null) {
                JOptionPane.showMessageDialog(null, "No se pudo encontrar el prestamo con los datos ingresados.", "iBooking", JOptionPane.ERROR_MESSAGE);
                txtFldUsuario_DevolucionPanel.requestFocus();
                return;
            }

            //Transaccion efectiva de devolucion de libro:
            prestamoActual.setDate_return(Utilidades.getFechaActual());
            daoPrestamos.Modificar(prestamoActual);

            //Modificacion del stock (Incremento):
            libroActual.setAvailable(libroActual.getAvailable() + 1);
            daoLibros.Modificar(libroActual);

            //Anuncio pop-up de confirmacion:
            JOptionPane.showMessageDialog(null, "El libro de ID: " + libroActual.getId() + " fue devuelto exitosamente por el usuario: " + usuarioActual.getName(), "iBooking", JOptionPane.INFORMATION_MESSAGE);
            txtFldUsuario_DevolucionPanel.setText("");
            txtFldLibroID_DevolucionPanel.setText("");
            txtFldUsuario_DevolucionPanel.requestFocus();

            //Verificacion de posibles sancionamientos:
            int dias = Utilidades.diferenciaDeFechas(Utilidades.StringToDate(prestamoActual.getDate_out()), new Date());

            //Sancionamiento en caso de exceso de dias:
            if (dias > dia_max_devolucion) {
                //Logica de costo:
                int dias_retraso = dias - dia_max_devolucion;
                int sancionamiento = dias_retraso * sancion_costo_por_dia;

                //Sancionamiento del usuario y adicion del dinero:
                usuarioActual.setSanctions(usuarioActual.getSanctions() + 1);
                usuarioActual.setSanc_money(usuarioActual.getSanc_money() + sancionamiento);
                daoUsuarios.sancionar(usuarioActual);
                JOptionPane.showMessageDialog(null, "Sancion aplicada al usuario: " + usuarioActual.getName() + " por ENTREGA A DESTIEMPO" + "\nSe aplicara una penalidad de S/" + sancionamiento + " soles.", "iBooking", JOptionPane.INFORMATION_MESSAGE);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Oops, ocurrio un error al devolver el libro.", "iBooking", JOptionPane.ERROR_MESSAGE);
            System.out.println(e.getMessage());
            //CHECKPOINT: Domingo, 09/02/2025 - 10:23
            //NOTA: Verificacion de cada paquete, y sus analisis independiente.
        }
    }//GEN-LAST:event_btnDevolver_DevolucionPanelActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDevolver_DevolucionPanel;
    private javax.swing.JSeparator jSeparator1_DevolucionPanel;
    private javax.swing.JSeparator jSeparator2_DevolucionPanel;
    private javax.swing.JSeparator jSeparator3_DevolucionPanel;
    private javax.swing.JLabel lblFolioUsuario_DevolucionPanel;
    private javax.swing.JLabel lblLibroID_DevolucionPanel;
    private javax.swing.JLabel lblTitle_DevolucionPanel;
    private javax.swing.JLabel lblimagen_DevolucionPanel;
    private javax.swing.JPanel pnlBackground_DevolucionPanel;
    private javax.swing.JTextField txtFldLibroID_DevolucionPanel;
    private javax.swing.JTextField txtFldUsuario_DevolucionPanel;
    // End of variables declaration//GEN-END:variables
}
