/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Views_panels;
//Importaciones de generales para el facil acceso a metodos y atributos:

import java.awt.Color;
import javax.swing.JOptionPane;
import Interfaces.*;
import View.*;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Fabrizio
 */
public class Libros extends javax.swing.JPanel {

    /**
     * Creates new form prinicipal
     */
    public Libros() {
        initComponents();
        //Metodo insertor de imagen:
        //ImageIcon();
        //Estilos del panel:
        InitStylesPanel();
        //Cargado de libros
        LoadLibros();
        //Quitar el metodo en caso no sea necesario, por el momento, se esta implementando con fines esteticos:
        //tblBuscarLibro_LibrosPanel.setEnabled(false);
        //jScrollPane1_LibrosPanel.setEnabled(false);
    }

    //Metodo de cargador/refrescado de libros del sistema:
    private void LoadLibros() {
        try {
            //Comunicacion con la base de datos:
            DAOLibros dao = new DAOLibrosImp();
            DefaultTableModel model = (DefaultTableModel) tblBuscarLibro_LibrosPanel.getModel();
            //Valores de inicializacion para el conteo de filas:
            model.setRowCount(0);
            //Listado de columnas de la tabla:
            dao.Listar("").forEach((u) -> model.addRow(new Object[]{u.getId(), u.getTitle(), u.getfecha(), u.getAuthor(),
                u.getCategory(), u.getEdit(), u.getLang(), u.getPages(), u.getDescripcion(), u.getEjemplares(), u.getStock(), u.getAvailable()}));
        } catch (Exception e) {
            //Captura del mensaje de error tras despliegue de accionamiento:
            System.out.println(e.getMessage());
        }
    }

    //Estilos para el panel DEVOLUCIONES:
    private void InitStylesPanel() {
        lblTitle_LibrosPanel.putClientProperty("FlatLaf.styleClass", "h1");
        //Mas metodos ha incluir(Opcional).
        //Generador de leyenda en JTextField
        txtBusqueda_LibrosPanel.putClientProperty("JTextField.placeholderText", "Ingrese el nombre del libro a buscar");
    }

    //Metodo de imagen:
    //Al ser un panel refactor del otro, copia todo su codigo
    //NOTA: No afecta en mucho si es que esta bien codificado.
    //private void ImageIcon() {
        //Metodo fallido de insercion de imagen:
        /*        
        URL imageURL = getClass().getResource("/Images/EBSCO-LISTA-344x258-c-default.jpg");
        if (imageURL != null) {
            Icon mIcon = new ImageIcon(new ImageIcon("/Images/EBSCO-LISTA-344x258-c-default.jpg").getImage().getScaledInstance(lblimageIcon.getWidth(), lblimageIcon.getHeight(), Image.SCALE_SMOOTH));
            lblimageIcon.setIcon(mIcon);  // Asegura que el ícono se establezca en el JLabel
        } else {
            System.out.println("Image not found!");
        }
         */
        //Solucion:
        //Insercion deesde icons por URL externa.
    //}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlBackground_LibrosPanel = new javax.swing.JPanel();
        lblTitle_LibrosPanel = new javax.swing.JLabel();
        txtBusqueda_LibrosPanel = new javax.swing.JTextField();
        btnBuscar_LibrosPanel = new javax.swing.JButton();
        jSeparator1_LibrosPanel = new javax.swing.JSeparator();
        jScrollPane1_LibrosPanel = new javax.swing.JScrollPane();
        tblBuscarLibro_LibrosPanel = new javax.swing.JTable();
        jSeparator2_LibrosPanel = new javax.swing.JSeparator();
        btnNuevo_LibrosPanel = new javax.swing.JButton();
        btnEditar_LibrosPanel = new javax.swing.JButton();
        btnBorrar_LibrosPanel = new javax.swing.JButton();

        pnlBackground_LibrosPanel.setBackground(new java.awt.Color(255, 255, 255));
        pnlBackground_LibrosPanel.setMinimumSize(new java.awt.Dimension(0, 0));
        pnlBackground_LibrosPanel.setPreferredSize(new java.awt.Dimension(0, 0));

        lblTitle_LibrosPanel.setForeground(new java.awt.Color(0, 0, 0));
        lblTitle_LibrosPanel.setText("BUSQUEDA DE LIBROS");

        btnBuscar_LibrosPanel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnBuscar_LibrosPanel.setText("BUSCAR");
        btnBuscar_LibrosPanel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnBuscar_LibrosPanel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscar_LibrosPanelActionPerformed(evt);
            }
        });

        jSeparator1_LibrosPanel.setForeground(new java.awt.Color(204, 204, 204));

        tblBuscarLibro_LibrosPanel.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "TITULO", "FECHA DE PUBLICACION", "AUTOR", "CATEGORIA", "EDICION", "IDIOMA", "PAGINAS", "DESCRIPCION", "EJEMPLARES", "STOCK", "DISPONIBILIDAD"
            }
        ));
        jScrollPane1_LibrosPanel.setViewportView(tblBuscarLibro_LibrosPanel);

        jSeparator2_LibrosPanel.setForeground(new java.awt.Color(204, 204, 204));

        btnNuevo_LibrosPanel.setText("NUEVO");
        btnNuevo_LibrosPanel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevo_LibrosPanelActionPerformed(evt);
            }
        });

        btnEditar_LibrosPanel.setText("EDITAR");
        btnEditar_LibrosPanel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditar_LibrosPanelActionPerformed(evt);
            }
        });

        btnBorrar_LibrosPanel.setText("BORRAR");

        javax.swing.GroupLayout pnlBackground_LibrosPanelLayout = new javax.swing.GroupLayout(pnlBackground_LibrosPanel);
        pnlBackground_LibrosPanel.setLayout(pnlBackground_LibrosPanelLayout);
        pnlBackground_LibrosPanelLayout.setHorizontalGroup(
            pnlBackground_LibrosPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBackground_LibrosPanelLayout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(pnlBackground_LibrosPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(pnlBackground_LibrosPanelLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(lblTitle_LibrosPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 705, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnlBackground_LibrosPanelLayout.createSequentialGroup()
                        .addGroup(pnlBackground_LibrosPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(pnlBackground_LibrosPanelLayout.createSequentialGroup()
                                .addComponent(txtBusqueda_LibrosPanel)
                                .addGap(18, 18, 18)
                                .addComponent(btnBuscar_LibrosPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane1_LibrosPanel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 705, Short.MAX_VALUE)
                            .addComponent(jSeparator1_LibrosPanel, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlBackground_LibrosPanelLayout.createSequentialGroup()
                                .addComponent(btnNuevo_LibrosPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnEditar_LibrosPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnBorrar_LibrosPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jSeparator2_LibrosPanel))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(50, 50, 50))
        );
        pnlBackground_LibrosPanelLayout.setVerticalGroup(
            pnlBackground_LibrosPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBackground_LibrosPanelLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(lblTitle_LibrosPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(7, 7, 7)
                .addGroup(pnlBackground_LibrosPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnBuscar_LibrosPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
                    .addComponent(txtBusqueda_LibrosPanel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1_LibrosPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1_LibrosPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jSeparator2_LibrosPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlBackground_LibrosPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnNuevo_LibrosPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEditar_LibrosPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBorrar_LibrosPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(29, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlBackground_LibrosPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 801, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlBackground_LibrosPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 430, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnBuscar_LibrosPanelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscar_LibrosPanelActionPerformed
        //Accionamiento de busqueda de libros:
        //Viernes 24/01/2025
        try {
            //String de consulta en la base de datos:
            String BusquedaLibro = txtBusqueda_LibrosPanel.getText();
            //Validacion de busqueda:
            if (BusquedaLibro.isEmpty()) {
                JOptionPane.showMessageDialog(null, "Por favor, ingrese el nombre del libro a buscar.", "iBooking", JOptionPane.WARNING_MESSAGE);
                txtBusqueda_LibrosPanel.requestFocus();
                return;
            }
            //Comunicacion con los DAO:
            DAOLibros dao = new DAOLibrosImp();
            //Inicializacion de la tabla:
            DefaultTableModel model = (DefaultTableModel) tblBuscarLibro_LibrosPanel.getModel();
            //Valores de inicializacion para el conteo de filas:
            model.setRowCount(0);
            //Listado de columnas de la tabla:
            dao.Listar(BusquedaLibro).forEach((u) -> model.addRow(new Object[]{u.getId(), u.getTitle(), u.getfecha(), u.getAuthor(),
                u.getCategory(), u.getEdit(), u.getLang(), u.getPages(), u.getDescripcion(), u.getEjemplares(), u.getStock(), u.getAvailable()}));
        } catch (Exception e) {
            System.out.println(e.getMessage());
        }
    }//GEN-LAST:event_btnBuscar_LibrosPanelActionPerformed

    private void btnNuevo_LibrosPanelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevo_LibrosPanelActionPerformed
        //Muestra del panel de agreagacion de libros:
        View.View1.showJPanel(new AdicionesLibro());
    }//GEN-LAST:event_btnNuevo_LibrosPanelActionPerformed

    private void btnEditar_LibrosPanelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditar_LibrosPanelActionPerformed
        //CHECOKPOINT: Miercoles, 29/01/2025 - 07:18
        //NOTA: Arreglar la funcionalidad del boton "EDITAR", al momento de el accionamiento,
        //      ejecuta el error: "Parameter index out of range (1 > number of parameters, which is 0)."
        //      Tomar el ejemplo del panel AdicionesUsuarios.java y Usuarios.java

        //CHECKPOINT: Jueves, 30/01/2025 - 
        //NOTA: Problema de funcionalidad, al parecer se refiere a la carencia de la implementacion de la funcionalidad en la
        //      clase DAOLibrosImp.java, correccion de la confusion
        if (tblBuscarLibro_LibrosPanel.getSelectedRow() > -1) {
            try {
                int libroId = (int) tblBuscarLibro_LibrosPanel.getValueAt(tblBuscarLibro_LibrosPanel.getSelectedRow(), 0);
                DAOLibros dao = new DAOLibrosImp();
                View.View1.showJPanel(new AdicionesLibro(dao.getLibrobyID(libroId)));
            } catch (Exception e) {
                System.out.println(e.getMessage());
            }
        } else {
            JOptionPane.showMessageDialog(null, "Debe seleccionar un libro a ser editado.", "iBooking", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_btnEditar_LibrosPanelActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBorrar_LibrosPanel;
    private javax.swing.JButton btnBuscar_LibrosPanel;
    private javax.swing.JButton btnEditar_LibrosPanel;
    private javax.swing.JButton btnNuevo_LibrosPanel;
    private javax.swing.JScrollPane jScrollPane1_LibrosPanel;
    private javax.swing.JSeparator jSeparator1_LibrosPanel;
    private javax.swing.JSeparator jSeparator2_LibrosPanel;
    private javax.swing.JLabel lblTitle_LibrosPanel;
    private javax.swing.JPanel pnlBackground_LibrosPanel;
    private javax.swing.JTable tblBuscarLibro_LibrosPanel;
    private javax.swing.JTextField txtBusqueda_LibrosPanel;
    // End of variables declaration//GEN-END:variables
}
