/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Views_panels;
//Importaciones de generales para el facil acceso a metodos y atributos:

import Interfaces.*;
import java.awt.Color;
import javax.swing.JOptionPane;
import Utilities.*;
import View.*;

/**
 *
 * @author Fabrizio
 */
public class Prestamos extends javax.swing.JPanel {

    //Variables globales:
    //boolean isEdition = true;
    /**
     * Creates new form prinicipal
     */
    public Prestamos() {
        initComponents();
        //Metodo insertor de imagen:
        //ImageIcon();
        //Estilos del panel:
        InitStylesPanel();
    }

    //CHECKPOINT: Domingo 12/01/2025 - 19:13, implementar las funcionalidades para los demas paneles de interaccion. 
    //Estilos para el panel PRESTAMO:
    private void InitStylesPanel() {
        lblTitle_PrestamosPanel.putClientProperty("FlatLaf.styleClass", "h1");
        //Mas metodos ha incluir(Opcional).
        //Generador de leyendas en los JTextField
        txtFldUsuario_PrestamosPanel.putClientProperty("JTextField.placeholderText", "Ingrese el folio de usuario");
        txtFldLibroID_PrestamosPanel.putClientProperty("JTextField.placeholderText", "Ingrese el ID del libro a prestar");
    }

    //Metodo de imagen:
    //metodo fallido de insercion de imagen:
    //private void ImageIcon() {
    //Metodo fallido:
    /*        
        URL imageURL = getClass().getResource("/Images/EBSCO-LISTA-344x258-c-default.jpg");
        if (imageURL != null) {
            Icon mIcon = new ImageIcon(new ImageIcon("/Images/EBSCO-LISTA-344x258-c-default.jpg").getImage().getScaledInstance(lblimageIcon.getWidth(), lblimageIcon.getHeight(), Image.SCALE_SMOOTH));
            lblimageIcon.setIcon(mIcon);  // Asegura que el ícono se establezca en el JLabel
        } else {
            System.out.println("Image not found!");
        }
     */
    //Solucion:
    //Insercion deesde icons por URL externa.
    //}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlBackground_PrestamosPanel = new javax.swing.JPanel();
        lblTitle_PrestamosPanel = new javax.swing.JLabel();
        lblFolioUsuario_PrestamosPanel = new javax.swing.JLabel();
        txtFldUsuario_PrestamosPanel = new javax.swing.JTextField();
        jSeparator2_PrestamosPanel = new javax.swing.JSeparator();
        lblLibroID_PrestamosPanel = new javax.swing.JLabel();
        txtFldLibroID_PrestamosPanel = new javax.swing.JTextField();
        jSeparator3_PrestamosPanel = new javax.swing.JSeparator();
        btnPrestar_PrestamosPanel = new javax.swing.JButton();
        jSeparator1_PrestamosPanel = new javax.swing.JSeparator();
        lblimagen_PrestamosPanel = new javax.swing.JLabel();

        pnlBackground_PrestamosPanel.setBackground(new java.awt.Color(255, 255, 255));
        pnlBackground_PrestamosPanel.setMinimumSize(new java.awt.Dimension(0, 0));
        pnlBackground_PrestamosPanel.setPreferredSize(new java.awt.Dimension(0, 0));

        lblTitle_PrestamosPanel.setForeground(new java.awt.Color(0, 0, 0));
        lblTitle_PrestamosPanel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitle_PrestamosPanel.setText("PRESTAMOS");

        lblFolioUsuario_PrestamosPanel.setForeground(new java.awt.Color(0, 0, 0));
        lblFolioUsuario_PrestamosPanel.setText("FOLIO DE USUARIO:");

        jSeparator2_PrestamosPanel.setForeground(new java.awt.Color(204, 204, 204));

        lblLibroID_PrestamosPanel.setForeground(new java.awt.Color(0, 0, 0));
        lblLibroID_PrestamosPanel.setText("LIBRO ID:");

        jSeparator3_PrestamosPanel.setForeground(new java.awt.Color(204, 204, 204));

        btnPrestar_PrestamosPanel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnPrestar_PrestamosPanel.setText("PRESTAR");
        btnPrestar_PrestamosPanel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnPrestar_PrestamosPanel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrestar_PrestamosPanelActionPerformed(evt);
            }
        });

        jSeparator1_PrestamosPanel.setForeground(new java.awt.Color(204, 204, 204));
        jSeparator1_PrestamosPanel.setOrientation(javax.swing.SwingConstants.VERTICAL);

        lblimagen_PrestamosPanel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblimagen_PrestamosPanel.setIcon(new javax.swing.ImageIcon("C:\\Users\\Fabrizio\\OneDrive\\Documentos\\ToGit - NetBeans\\LibraryManagement_System\\Program_Images\\DSC0485-Edit.jpg")); // NOI18N

        javax.swing.GroupLayout pnlBackground_PrestamosPanelLayout = new javax.swing.GroupLayout(pnlBackground_PrestamosPanel);
        pnlBackground_PrestamosPanel.setLayout(pnlBackground_PrestamosPanelLayout);
        pnlBackground_PrestamosPanelLayout.setHorizontalGroup(
            pnlBackground_PrestamosPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBackground_PrestamosPanelLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(lblimagen_PrestamosPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 390, Short.MAX_VALUE)
                .addGap(31, 31, 31)
                .addComponent(jSeparator1_PrestamosPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addGroup(pnlBackground_PrestamosPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTitle_PrestamosPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jSeparator2_PrestamosPanel)
                    .addComponent(jSeparator3_PrestamosPanel)
                    .addComponent(btnPrestar_PrestamosPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblFolioUsuario_PrestamosPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 270, Short.MAX_VALUE)
                    .addComponent(lblLibroID_PrestamosPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtFldUsuario_PrestamosPanel)
                    .addComponent(txtFldLibroID_PrestamosPanel))
                .addGap(50, 50, 50))
        );
        pnlBackground_PrestamosPanelLayout.setVerticalGroup(
            pnlBackground_PrestamosPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBackground_PrestamosPanelLayout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addComponent(lblTitle_PrestamosPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblFolioUsuario_PrestamosPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtFldUsuario_PrestamosPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2_PrestamosPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 10, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblLibroID_PrestamosPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtFldLibroID_PrestamosPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator3_PrestamosPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 10, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(btnPrestar_PrestamosPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(96, 96, 96))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlBackground_PrestamosPanelLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(pnlBackground_PrestamosPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jSeparator1_PrestamosPanel)
                    .addComponent(lblimagen_PrestamosPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(19, 19, 19))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlBackground_PrestamosPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 800, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlBackground_PrestamosPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 430, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnPrestar_PrestamosPanelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrestar_PrestamosPanelActionPerformed
        //Checkpoint: Domingo, 26/01/2025
        //Inicializacion de objetos:
        String folioUsuario = txtFldUsuario_PrestamosPanel.getText();
        String libroId = txtFldLibroID_PrestamosPanel.getText();
        //Barrera de parametros - filtros de campos:
        if (folioUsuario.isEmpty() || libroId.isEmpty()) {
            //Panel pop-up de advertencia:
            JOptionPane.showMessageDialog(null, "Por favor, completar todos los campos", "iBooking", JOptionPane.WARNING_MESSAGE);
            //CHECKPOINT: Miercoles, 05/02/2025
            //NOTA: Complementacion de los campos de entrada de texto (Amplificacion de parametrizacion de campos)
            txtFldUsuario_PrestamosPanel.requestFocus();
            return;
            /*
            Prototipo de autorellenado de campos tras confirmacion de trannsaccion exitosa:
            METODO FALLIDO, NO USAR:
            if (!isEdition) {
                txtFldUsuario_PrestamosPanel.setTex
                txtFldUsuario_PrestamosPanel.requestFocus();
            }
             */
        } else if (!Utilidades.isNumeric(folioUsuario) || !Utilidades.isNumeric(libroId)) {
            JOptionPane.showMessageDialog(null, "Los campos de ingreso de texto de FOLIO y el ID dek libro deben ser numeros enteros.", "iBooking", JOptionPane.ERROR_MESSAGE);
            txtFldUsuario_PrestamosPanel.requestFocus();
            return;
            //NOTA: Cambio de localizacion, redireccion al "try{...}..." 
            /*
            JOptionPane.showMessageDialog(null, "Se ha registrado su prestamo, gracias. Buen dia :)", "iBooking", JOptionPane.INFORMATION_MESSAGE);
            //Limpiado de campos de texto tras operacion exitosa:
            txtFldUsuario_PrestamosPanel.setText("");
            txtFldLibroID_PrestamosPanel.setText("");
            txtFldUsuario_PrestamosPanel.requestFocus();
             */
        } else if (Integer.parseInt(folioUsuario) <= 0 || Integer.parseInt(libroId) <= 0) {
            JOptionPane.showMessageDialog(null, "Los campos de ingreso de texto de FOLIO y el ID dek libro deben ser mayores que 0.", "iBooking", JOptionPane.ERROR_MESSAGE);
            return;
        }

        try {
            //NOTA: Validacion de existencias de usuarios, libros y prestamos
            Interfaces.DAOUsuarios daoUsuarios = new DAOUsuariosImpl();
            //Comunicacion y transformacion de campos:
            DataBase_Models.Usuarios usuarioActual = daoUsuarios.getUsuarioByID(Integer.parseInt(folioUsuario));
            //Validacion para los usuarios:
            if (usuarioActual == null) {
                JOptionPane.showMessageDialog(null, "No se encontro ningun usuario con ese folio.", "iBooking", JOptionPane.ERROR_MESSAGE);
                txtFldUsuario_PrestamosPanel.requestFocus();
                return;
            }
            //Validacion para los libros:
            DAOLibros daoLibros = new DAOLibrosImp();
            //CHECKPOINT: Miercoles, 05/02/2025 - 22:03
            //NOTA: Continuacion de implementacion de las validaciones de entrada de campos de texto.

            //CHECKPOINT: Sabado, 08/02/2025
            //Validacion de entrada de texto para la seccion de libros:
            DataBase_Models.Libros libroActual = daoLibros.getLibrobyID(Integer.parseInt(libroId));
            if (libroActual == null) {
                JOptionPane.showMessageDialog(null, "No se encontro ningun libro con ese ID", "iBooking", JOptionPane.ERROR_MESSAGE);
                txtFldLibroID_PrestamosPanel.requestFocus();
                return;
            } else if (libroActual.getAvailable() < 1) {
                JOptionPane.showMessageDialog(null, "Ya no se cuenta con unidades disponibles para su prestamos con ese ID.", "iBooking", JOptionPane.ERROR_MESSAGE);
                txtFldLibroID_PrestamosPanel.requestFocus();
                return;
            }

            //Validacion de prestamos de un usuario:
            DAOPrestamos daoPrestamos = new DAOPrestamosImp();
            DataBase_Models.Prestamos prestamoActual = daoPrestamos.getPrestamos(usuarioActual, libroActual);
            //Campos de validacion de entrada de informacion:
            if (prestamoActual != null) {
                JOptionPane.showMessageDialog(null, "La persona ya cuenta con el prestamo del mismo libro.", "iBooking", JOptionPane.ERROR_MESSAGE);
                txtFldLibroID_PrestamosPanel.requestFocus();
                return;
            }
            //Se acepta el acceso al libro en caso se pase el parametro anterior:
            DataBase_Models.Prestamos prestamos = new DataBase_Models.Prestamos();
            //Set de informacion en los parametros establecidos:
            prestamos.setBook_id(libroActual.getId());
            prestamos.setUsers_id(usuarioActual.getId());
            prestamos.setDate_out(Utilities.Utilidades.getFechaActual());
            //Ejecucion del comando y registor en la base de datos:
            daoPrestamos.Registrar(prestamos);
            //Contador de aumento o resta para el libro solicitado segun el stock total:
            libroActual.setAvailable(libroActual.getAvailable() - 1);
            daoLibros.Modificar(libroActual);
            //Mensaje de alerta:
            JOptionPane.showMessageDialog(null, "El libro con ID: " + libroActual.getId() + " se ha prestado exitosamente a el usuario: " + usuarioActual.getName(), "iBooking", JOptionPane.INFORMATION_MESSAGE);
            //Limpiado de campos de texto tras operacion exitosa:
            txtFldUsuario_PrestamosPanel.setText("");
            txtFldLibroID_PrestamosPanel.setText("");
            txtFldUsuario_PrestamosPanel.requestFocus();
        } catch (Exception e) {
            //Captura del posible mensaje de error en consola tras despliegue de accionamiento:
            JOptionPane.showMessageDialog(null, "Oops, ocurrio un error al prestar el libro.", "iBooking", JOptionPane.ERROR_MESSAGE);
            System.out.println(e.getMessage());
        }
    }//GEN-LAST:event_btnPrestar_PrestamosPanelActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnPrestar_PrestamosPanel;
    private javax.swing.JSeparator jSeparator1_PrestamosPanel;
    private javax.swing.JSeparator jSeparator2_PrestamosPanel;
    private javax.swing.JSeparator jSeparator3_PrestamosPanel;
    private javax.swing.JLabel lblFolioUsuario_PrestamosPanel;
    private javax.swing.JLabel lblLibroID_PrestamosPanel;
    private javax.swing.JLabel lblTitle_PrestamosPanel;
    private javax.swing.JLabel lblimagen_PrestamosPanel;
    private javax.swing.JPanel pnlBackground_PrestamosPanel;
    private javax.swing.JTextField txtFldLibroID_PrestamosPanel;
    private javax.swing.JTextField txtFldUsuario_PrestamosPanel;
    // End of variables declaration//GEN-END:variables
}
