/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Views_panels;
//Importaciones de generales para el facil acceso a metodos y atributos:

import DataBase_Models.*;
import Interfaces.*;
import Utilities.*;
import View.*;
import Views_panels.*;
import java.awt.Color;

/**
 *
 * @author Fabrizio
 */
public class prinicipal extends javax.swing.JPanel {

    /**
     * Creates new form prinicipal
     */
    public prinicipal() {
        initComponents();
        //Estilos del panel:
        InitStylesPanel();
    }

    //Estilos para el panel PRINCIPAL:
    private void InitStylesPanel() {
        //Encabezado:
        lblTitle_PrincipalPanel.putClientProperty("FlatLaf.styleClass", "h1");
        lblTitle_PrincipalPanel.setForeground(Color.black);
        lblSubTitle_PrincipalPanel.putClientProperty("FlatLaf.styleClass", "h3");
        lblSubTitle_PrincipalPanel.setForeground(Color.black);
        //Agregar mas tipos de campos para la estilizacion con FlatLaf
        //Cuerpo:
        lblTexto1_PrincipalPanel.putClientProperty("FlatLaf.styleClass", "large");
        lblTexto1_PrincipalPanel.setForeground(Color.black);
        lblTexto2_PrincipalPanel.putClientProperty("FlatLaf.styleClass", "large");
        lblTexto2_PrincipalPanel.setForeground(Color.black);
        lblTexto3_PrincipalPanel.putClientProperty("FlatLaf.styleClass", "large");
        lblTexto3_PrincipalPanel.setForeground(Color.black);
        lblTexto4_PrincipalPanel.putClientProperty("FlatLaf.styleClass", "large");
        lblTexto4_PrincipalPanel.setForeground(Color.black);
        lblTexto5_PrincipalPanel.putClientProperty("FlatLaf.styleClass", "large");
        lblTexto5_PrincipalPanel.setForeground(Color.black);
        lblTexto6_PrincipalPanel.putClientProperty("FlatLaf.styleClass", "large");
        lblTexto6_PrincipalPanel.setForeground(Color.black);
        lblTexto7_PrincipalPanel.putClientProperty("FlatLaf.styleClass", "large");
        lblTexto7_PrincipalPanel.setForeground(Color.black);
        lblTexto8_PrincipalPanel.putClientProperty("FlatLaf.styleClass", "large");
        lblTexto8_PrincipalPanel.setForeground(Color.black);
        lblTexto9_PrincipalPanel.putClientProperty("FlatLaf.styleClass", "large");
        lblTexto9_PrincipalPanel.setForeground(Color.black);
        lblTexto10_PrincipalPanel.putClientProperty("FlatLaf.styleClass", "large");
        lblTexto10_PrincipalPanel.setForeground(Color.black);
        lblTexto11_PrincipalPanel.putClientProperty("FlatLaf.styleClass", "large");
        lblTexto11_PrincipalPanel.setForeground(Color.black);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlBackground_PrincipalPanel = new javax.swing.JPanel();
        lblTitle_PrincipalPanel = new javax.swing.JLabel();
        lblSubTitle_PrincipalPanel = new javax.swing.JLabel();
        lblTexto1_PrincipalPanel = new javax.swing.JLabel();
        lblTexto2_PrincipalPanel = new javax.swing.JLabel();
        lblTexto3_PrincipalPanel = new javax.swing.JLabel();
        lblTexto4_PrincipalPanel = new javax.swing.JLabel();
        lblTexto5_PrincipalPanel = new javax.swing.JLabel();
        lblTexto6_PrincipalPanel = new javax.swing.JLabel();
        lblTexto7_PrincipalPanel = new javax.swing.JLabel();
        lblTexto8_PrincipalPanel = new javax.swing.JLabel();
        lblTexto9_PrincipalPanel = new javax.swing.JLabel();
        lblTexto10_PrincipalPanel = new javax.swing.JLabel();
        lblTexto11_PrincipalPanel = new javax.swing.JLabel();
        jSeparator1_PrincipalPanel = new javax.swing.JSeparator();
        lblimage_PrincipalPanel = new javax.swing.JLabel();
        jSeparator2_PrincipalPanel = new javax.swing.JSeparator();

        pnlBackground_PrincipalPanel.setBackground(new java.awt.Color(255, 255, 255));
        pnlBackground_PrincipalPanel.setMinimumSize(new java.awt.Dimension(0, 0));
        pnlBackground_PrincipalPanel.setPreferredSize(new java.awt.Dimension(0, 0));

        lblTitle_PrincipalPanel.setForeground(new java.awt.Color(0, 0, 0));
        lblTitle_PrincipalPanel.setText("iBooking");

        lblSubTitle_PrincipalPanel.setForeground(new java.awt.Color(0, 0, 0));
        lblSubTitle_PrincipalPanel.setText("BIENVENIDO A LA GESTOR VIRTUAL DE LA LIBRERIA");

        lblTexto1_PrincipalPanel.setForeground(new java.awt.Color(0, 0, 0));
        lblTexto1_PrincipalPanel.setText("Sistema de Gestion para Biblioteca Publica. Controle y administre");

        lblTexto2_PrincipalPanel.setForeground(new java.awt.Color(0, 0, 0));
        lblTexto2_PrincipalPanel.setText("de forma optima y facil el flujo de prestamos y devoluciones de libros");

        lblTexto3_PrincipalPanel.setForeground(new java.awt.Color(0, 0, 0));
        lblTexto3_PrincipalPanel.setText("Esta herramienta le permitira llevar un control completo y detallado de");

        lblTexto4_PrincipalPanel.setForeground(new java.awt.Color(0, 0, 0));
        lblTexto4_PrincipalPanel.setText("su biblioteca. Tendra acceso a herramientas especiales para tareas");

        lblTexto5_PrincipalPanel.setForeground(new java.awt.Color(0, 0, 0));
        lblTexto5_PrincipalPanel.setText("especificas, como lo son:");

        lblTexto6_PrincipalPanel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblTexto6_PrincipalPanel.setForeground(new java.awt.Color(0, 0, 0));
        lblTexto6_PrincipalPanel.setText("- PRESTAMOS");

        lblTexto7_PrincipalPanel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblTexto7_PrincipalPanel.setForeground(new java.awt.Color(0, 0, 0));
        lblTexto7_PrincipalPanel.setText("- DEVOLUCIONES");

        lblTexto8_PrincipalPanel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblTexto8_PrincipalPanel.setForeground(new java.awt.Color(0, 0, 0));
        lblTexto8_PrincipalPanel.setText("- REGISTRO DE USUARIOS Y LIBROS NUEVOS");

        lblTexto9_PrincipalPanel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblTexto9_PrincipalPanel.setForeground(new java.awt.Color(0, 0, 0));
        lblTexto9_PrincipalPanel.setText("- EDICION DE USUARIOS Y LIBROS EXISTENTES");

        lblTexto10_PrincipalPanel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblTexto10_PrincipalPanel.setForeground(new java.awt.Color(0, 0, 0));
        lblTexto10_PrincipalPanel.setText("- ELIMINAR TODO TIPO DE REGISTROS");

        lblTexto11_PrincipalPanel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblTexto11_PrincipalPanel.setForeground(new java.awt.Color(0, 0, 0));
        lblTexto11_PrincipalPanel.setText("- SECCION DE REPORTES DE ACCIONES EN EL SISTEMA");

        jSeparator1_PrincipalPanel.setForeground(new java.awt.Color(204, 204, 204));

        lblimage_PrincipalPanel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblimage_PrincipalPanel.setIcon(new javax.swing.ImageIcon("C:\\Users\\Fabrizio\\OneDrive\\Documentos\\ToGit - NetBeans\\LibraryManagement_System\\Program_Images\\EBSCO-LISTA-344x258-c-default.jpg")); // NOI18N

        jSeparator2_PrincipalPanel.setForeground(new java.awt.Color(204, 204, 204));

        javax.swing.GroupLayout pnlBackground_PrincipalPanelLayout = new javax.swing.GroupLayout(pnlBackground_PrincipalPanel);
        pnlBackground_PrincipalPanel.setLayout(pnlBackground_PrincipalPanelLayout);
        pnlBackground_PrincipalPanelLayout.setHorizontalGroup(
            pnlBackground_PrincipalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBackground_PrincipalPanelLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(pnlBackground_PrincipalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlBackground_PrincipalPanelLayout.createSequentialGroup()
                        .addComponent(lblTitle_PrincipalPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(pnlBackground_PrincipalPanelLayout.createSequentialGroup()
                        .addGroup(pnlBackground_PrincipalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblSubTitle_PrincipalPanel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblTexto1_PrincipalPanel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblTexto2_PrincipalPanel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblTexto3_PrincipalPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator1_PrincipalPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 335, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 32, 32))
                    .addGroup(pnlBackground_PrincipalPanelLayout.createSequentialGroup()
                        .addGroup(pnlBackground_PrincipalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblTexto7_PrincipalPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblTexto4_PrincipalPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 353, Short.MAX_VALUE)
                            .addComponent(lblTexto8_PrincipalPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblTexto9_PrincipalPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblTexto10_PrincipalPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblTexto11_PrincipalPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblTexto5_PrincipalPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblTexto6_PrincipalPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(53, 53, 53)
                        .addGroup(pnlBackground_PrincipalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlBackground_PrincipalPanelLayout.createSequentialGroup()
                                .addComponent(lblimage_PrincipalPanel)
                                .addContainerGap(32, Short.MAX_VALUE))
                            .addGroup(pnlBackground_PrincipalPanelLayout.createSequentialGroup()
                                .addComponent(jSeparator2_PrincipalPanel)
                                .addGap(13, 13, 13))))))
        );
        pnlBackground_PrincipalPanelLayout.setVerticalGroup(
            pnlBackground_PrincipalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBackground_PrincipalPanelLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(lblTitle_PrincipalPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblSubTitle_PrincipalPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblTexto1_PrincipalPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblTexto2_PrincipalPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlBackground_PrincipalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlBackground_PrincipalPanelLayout.createSequentialGroup()
                        .addComponent(jSeparator1_PrincipalPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblimage_PrincipalPanel)
                        .addGap(20, 20, 20)
                        .addComponent(jSeparator2_PrincipalPanel)
                        .addGap(28, 28, 28))
                    .addGroup(pnlBackground_PrincipalPanelLayout.createSequentialGroup()
                        .addComponent(lblTexto3_PrincipalPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblTexto4_PrincipalPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblTexto5_PrincipalPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(lblTexto6_PrincipalPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblTexto7_PrincipalPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblTexto8_PrincipalPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblTexto9_PrincipalPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblTexto10_PrincipalPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblTexto11_PrincipalPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(130, 130, 130))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlBackground_PrincipalPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 800, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlBackground_PrincipalPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 430, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSeparator jSeparator1_PrincipalPanel;
    private javax.swing.JSeparator jSeparator2_PrincipalPanel;
    private javax.swing.JLabel lblSubTitle_PrincipalPanel;
    private javax.swing.JLabel lblTexto10_PrincipalPanel;
    private javax.swing.JLabel lblTexto11_PrincipalPanel;
    private javax.swing.JLabel lblTexto1_PrincipalPanel;
    private javax.swing.JLabel lblTexto2_PrincipalPanel;
    private javax.swing.JLabel lblTexto3_PrincipalPanel;
    private javax.swing.JLabel lblTexto4_PrincipalPanel;
    private javax.swing.JLabel lblTexto5_PrincipalPanel;
    private javax.swing.JLabel lblTexto6_PrincipalPanel;
    private javax.swing.JLabel lblTexto7_PrincipalPanel;
    private javax.swing.JLabel lblTexto8_PrincipalPanel;
    private javax.swing.JLabel lblTexto9_PrincipalPanel;
    private javax.swing.JLabel lblTitle_PrincipalPanel;
    private javax.swing.JLabel lblimage_PrincipalPanel;
    private javax.swing.JPanel pnlBackground_PrincipalPanel;
    // End of variables declaration//GEN-END:variables
}
