/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Views_panels;
//Importaciones de generales para el facil acceso a metodos y atributos:

import java.awt.Color;
import javax.swing.table.DefaultTableModel;
import DataBase_Models.*;
import Interfaces.*;
import Utilities.*;
import Views_panels.*;
import View.*;

/**
 *
 * @author Fabrizio
 */
public class Reportes extends javax.swing.JPanel {

    /**
     * Creates new form prinicipal
     */
    public Reportes() {
        initComponents();
        //Metodo insertor de imagen:
        //ImageIcon();
        //Estilos del panel:
        InitStylesPanel();
        loadLending();
        //Bloqueo de la tabla var evitar alteraciones:
        tblReportes_ReportesPanel.setEnabled(false);
    }

    private void loadLending() {
        try {
            DAOPrestamos dao = new DAOPrestamosImp();
            DefaultTableModel model = (DefaultTableModel) tblReportes_ReportesPanel.getModel();
            //Limpieza de tabla:
            model.setRowCount(0);
            dao.Listar().forEach((u) -> model.addRow(new Object[]{u.getUsers_id(), u.getBook_id(), u.getDate_out(), u.getDate_return()}));
            //CHECKPOINT: Sabado, 08/02/2025 - 20:06
            //NOTA: Continuar la implementacion del panel de Reportes.
        } catch (Exception e) {
            //CHECKPOINT: Sabado, 08/02/2025 - 
            //NOTA: Continuacion de la estructura de la funcionalidad de Reportes.
            System.out.println(e.getMessage());
        }
    }

    //Estilos para el panel DEVOLUCIONES:
    private void InitStylesPanel() {
        lblTitle_ReportesPanel.putClientProperty("FlatLaf.styleClass", "h1");
        //Mas metodos ha incluir(Opcional).
        //DefaultTableModel model = (DefaultTableModel) tblReportes_ReportesPanel.getModel();
    }

    //Metodo de imagen:
    //Al ser un panel refactor del otro, copia todo su codigo
    //NOTA: No afecta en mucho si es que esta bien codificado.
    //metodo fallido de insercion de imagen:
    //private void ImageIcon() {
    //Metodo fallido:
    /*        
        URL imageURL = getClass().getResource("/Images/EBSCO-LISTA-344x258-c-default.jpg");
        if (imageURL != null) {
            Icon mIcon = new ImageIcon(new ImageIcon("/Images/EBSCO-LISTA-344x258-c-default.jpg").getImage().getScaledInstance(lblimageIcon.getWidth(), lblimageIcon.getHeight(), Image.SCALE_SMOOTH));
            lblimageIcon.setIcon(mIcon);  // Asegura que el ícono se establezca en el JLabel
        } else {
            System.out.println("Image not found!");
        }
     */
    //Solucion:
    //Insercion deesde icons por URL externa.
    //}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlBackground_ReportesPanel = new javax.swing.JPanel();
        lblTitle_ReportesPanel = new javax.swing.JLabel();
        jSeparator1_ReportesPanel = new javax.swing.JSeparator();
        jScrollPane1_ReportesPanel = new javax.swing.JScrollPane();
        tblReportes_ReportesPanel = new javax.swing.JTable();
        jSeparator2_ReportesPanel = new javax.swing.JSeparator();
        btnActualzar_ReportesPanel = new javax.swing.JButton();

        pnlBackground_ReportesPanel.setBackground(new java.awt.Color(255, 255, 255));
        pnlBackground_ReportesPanel.setMinimumSize(new java.awt.Dimension(0, 0));
        pnlBackground_ReportesPanel.setPreferredSize(new java.awt.Dimension(0, 0));

        lblTitle_ReportesPanel.setForeground(new java.awt.Color(0, 0, 0));
        lblTitle_ReportesPanel.setText("REPORTES DE ACTIVIDAD");

        jSeparator1_ReportesPanel.setForeground(new java.awt.Color(204, 204, 204));

        tblReportes_ReportesPanel.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "USERS_ID", "BOOK_ID", "FECHA DE SALIDA", "FECHA DE ENTREGA"
            }
        ));
        jScrollPane1_ReportesPanel.setViewportView(tblReportes_ReportesPanel);

        jSeparator2_ReportesPanel.setForeground(new java.awt.Color(204, 204, 204));

        btnActualzar_ReportesPanel.setText("ACTUALIZAR");
        btnActualzar_ReportesPanel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualzar_ReportesPanelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlBackground_ReportesPanelLayout = new javax.swing.GroupLayout(pnlBackground_ReportesPanel);
        pnlBackground_ReportesPanel.setLayout(pnlBackground_ReportesPanelLayout);
        pnlBackground_ReportesPanelLayout.setHorizontalGroup(
            pnlBackground_ReportesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBackground_ReportesPanelLayout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(pnlBackground_ReportesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(pnlBackground_ReportesPanelLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(lblTitle_ReportesPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 705, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnlBackground_ReportesPanelLayout.createSequentialGroup()
                        .addGroup(pnlBackground_ReportesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jScrollPane1_ReportesPanel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 705, Short.MAX_VALUE)
                            .addComponent(jSeparator1_ReportesPanel, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnActualzar_ReportesPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jSeparator2_ReportesPanel))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(50, 50, 50))
        );
        pnlBackground_ReportesPanelLayout.setVerticalGroup(
            pnlBackground_ReportesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBackground_ReportesPanelLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(lblTitle_ReportesPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1_ReportesPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1_ReportesPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator2_ReportesPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnActualzar_ReportesPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(29, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlBackground_ReportesPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 801, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlBackground_ReportesPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 430, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnActualzar_ReportesPanelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualzar_ReportesPanelActionPerformed
        //CHECKPOINT: Martes, 04/02/2025
        //NOTA: Implementacion de la funcionalidad para el boton "ACTUALIZAR" 
        //DefaultTableModel model = (DefaultTableModel) tblReportes_ReportesPanel.getModel();
        loadLending();
    }//GEN-LAST:event_btnActualzar_ReportesPanelActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualzar_ReportesPanel;
    private javax.swing.JScrollPane jScrollPane1_ReportesPanel;
    private javax.swing.JSeparator jSeparator1_ReportesPanel;
    private javax.swing.JSeparator jSeparator2_ReportesPanel;
    private javax.swing.JLabel lblTitle_ReportesPanel;
    private javax.swing.JPanel pnlBackground_ReportesPanel;
    private javax.swing.JTable tblReportes_ReportesPanel;
    // End of variables declaration//GEN-END:variables
}
