/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Views_panels;

//Importaciones de generales para el facil acceso a metodos y atributos:
import java.awt.Color;
import View.*;
import Interfaces.*;
import View.DAOUsuariosImpl;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
//import DataBase_Models.Usuarios;

/**
 *
 * @author Fabrizio
 */
public class Usuarios extends javax.swing.JPanel {

    /**
     * Creates new form prinicipal
     */
    public Usuarios() {
        initComponents();
        //Metodo insertor de imagen:
        //ImageIcon();
        //Estilos del panel:
        InitStylesPanel();
        //Metodo de carga de usuarios:
        LoadUsers();
    }

    //Cargado de usuarios tras presion del boton de accionamiento:
    private void LoadUsers() {
        try {
            DAOUsuarios dao = new DAOUsuariosImpl();
            //Instanciacion de la tabla a usar:
            DefaultTableModel model = (DefaultTableModel) tblUsuarios_UsuariosPanel.getModel();
            //Prueba en consola de la consulta "SELECT ....":
            //dao.Listar().forEach((u) -> System.out.println(u.getName()));
            dao.Listar("").forEach((u) -> model.addRow(new Object[]{u.getId(), u.getName(), u.getLast_name_p(), u.getLast_name_m(),
                u.getDomicilio(), u.getTel()}));
        } catch (Exception e) {
            System.out.println(e.getMessage());
        }
    }

    //Estilos para el panel DEVOLUCIONES:
    private void InitStylesPanel() {
        lblTitle_UsuariosPanel.putClientProperty("FlatLaf.styleClass", "h1");
        //Mas metodos de estilizado ha incluir(Opcional).
        //Generador de leyenda en el JTextField
        txtBusqueda_UsuariosPanel.putClientProperty("JTextField.placeholderText", "Ingrese el nombre de usuario a buscar");
    }

    //Metodo de imagen:
    //Al ser un panel refactor del otro, copia todo su codigo
    //NOTA: No afecta en mucho si es que esta bien codificado.
    //metodo fallido de insercion de imagen:
    //private void ImageIcon() {
    //Metodo fallido:
    /*        
        URL imageURL = getClass().getResource("/Images/EBSCO-LISTA-344x258-c-default.jpg");
        if (imageURL != null) {
            Icon mIcon = new ImageIcon(new ImageIcon("/Images/EBSCO-LISTA-344x258-c-default.jpg").getImage().getScaledInstance(lblimageIcon.getWidth(), lblimageIcon.getHeight(), Image.SCALE_SMOOTH));
            lblimageIcon.setIcon(mIcon);  // Asegura que el ícono se establezca en el JLabel
        } else {
            System.out.println("Image not found!");
        }
     */
    //Solucion:
    //Insercion deesde icons por URL externa.
    //}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlBackground_UsuariosPanel = new javax.swing.JPanel();
        lblTitle_UsuariosPanel = new javax.swing.JLabel();
        txtBusqueda_UsuariosPanel = new javax.swing.JTextField();
        btnBuscar_UsuariosPanel = new javax.swing.JButton();
        jSeparator1_UsuariosPanel = new javax.swing.JSeparator();
        jScrollPane1_UsuariosPanel = new javax.swing.JScrollPane();
        tblUsuarios_UsuariosPanel = new javax.swing.JTable();
        jSeparator2_UsuariosPanel = new javax.swing.JSeparator();
        btnNuevo_UsuariosPanel = new javax.swing.JButton();
        btnEditar_UsuariosPanel = new javax.swing.JButton();
        btnBorrar_UsuariosPanel = new javax.swing.JButton();

        pnlBackground_UsuariosPanel.setBackground(new java.awt.Color(255, 255, 255));
        pnlBackground_UsuariosPanel.setMinimumSize(new java.awt.Dimension(0, 0));
        pnlBackground_UsuariosPanel.setPreferredSize(new java.awt.Dimension(0, 0));

        lblTitle_UsuariosPanel.setForeground(new java.awt.Color(0, 0, 0));
        lblTitle_UsuariosPanel.setText("REPORTE DE USUARIOS");

        btnBuscar_UsuariosPanel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnBuscar_UsuariosPanel.setText("BUSCAR");
        btnBuscar_UsuariosPanel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnBuscar_UsuariosPanel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscar_UsuariosPanelActionPerformed(evt);
            }
        });

        jSeparator1_UsuariosPanel.setForeground(new java.awt.Color(204, 204, 204));

        tblUsuarios_UsuariosPanel.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "NOMBRE", "APELLIDO PATERNO", "APELLIDO MATERNO", "DOMICILIO", "TELEFONO"
            }
        ));
        jScrollPane1_UsuariosPanel.setViewportView(tblUsuarios_UsuariosPanel);

        jSeparator2_UsuariosPanel.setForeground(new java.awt.Color(204, 204, 204));

        btnNuevo_UsuariosPanel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnNuevo_UsuariosPanel.setText("NUEVO");
        btnNuevo_UsuariosPanel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevo_UsuariosPanelActionPerformed(evt);
            }
        });

        btnEditar_UsuariosPanel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnEditar_UsuariosPanel.setText("EDITAR");
        btnEditar_UsuariosPanel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditar_UsuariosPanelActionPerformed(evt);
            }
        });

        btnBorrar_UsuariosPanel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnBorrar_UsuariosPanel.setText("BORRAR");
        btnBorrar_UsuariosPanel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBorrar_UsuariosPanelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlBackground_UsuariosPanelLayout = new javax.swing.GroupLayout(pnlBackground_UsuariosPanel);
        pnlBackground_UsuariosPanel.setLayout(pnlBackground_UsuariosPanelLayout);
        pnlBackground_UsuariosPanelLayout.setHorizontalGroup(
            pnlBackground_UsuariosPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBackground_UsuariosPanelLayout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(pnlBackground_UsuariosPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(pnlBackground_UsuariosPanelLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(lblTitle_UsuariosPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 705, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnlBackground_UsuariosPanelLayout.createSequentialGroup()
                        .addGroup(pnlBackground_UsuariosPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(pnlBackground_UsuariosPanelLayout.createSequentialGroup()
                                .addComponent(txtBusqueda_UsuariosPanel)
                                .addGap(18, 18, 18)
                                .addComponent(btnBuscar_UsuariosPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane1_UsuariosPanel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 705, Short.MAX_VALUE)
                            .addComponent(jSeparator1_UsuariosPanel, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlBackground_UsuariosPanelLayout.createSequentialGroup()
                                .addComponent(btnNuevo_UsuariosPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnEditar_UsuariosPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnBorrar_UsuariosPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jSeparator2_UsuariosPanel))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(50, 50, 50))
        );
        pnlBackground_UsuariosPanelLayout.setVerticalGroup(
            pnlBackground_UsuariosPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBackground_UsuariosPanelLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(lblTitle_UsuariosPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(7, 7, 7)
                .addGroup(pnlBackground_UsuariosPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnBuscar_UsuariosPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
                    .addComponent(txtBusqueda_UsuariosPanel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1_UsuariosPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1_UsuariosPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jSeparator2_UsuariosPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlBackground_UsuariosPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnNuevo_UsuariosPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEditar_UsuariosPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBorrar_UsuariosPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(29, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlBackground_UsuariosPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 801, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlBackground_UsuariosPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 430, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnNuevo_UsuariosPanelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevo_UsuariosPanelActionPerformed
        //Metodo de llamado de otro panel dentro en un panel:
        //NOTA: Recoradar cambiar el codigo de los contenedores de []VACIO a []STATIC
        View1.showJPanel(new AdicionesUsuarios());
    }//GEN-LAST:event_btnNuevo_UsuariosPanelActionPerformed

    private void btnBorrar_UsuariosPanelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBorrar_UsuariosPanelActionPerformed
        //Instanciacion de la interface e Implementacion:
        DAOUsuarios dao = new DAOUsuariosImpl();
        DefaultTableModel model = (DefaultTableModel) tblUsuarios_UsuariosPanel.getModel();
        //Ciclo reutilizable de eliminacion con diferentes IDs:
        if (tblUsuarios_UsuariosPanel.getSelectedRows().length < 1) {
            JOptionPane.showMessageDialog(null, "Debe seleccionar uno o mas usuarios a eliminar", "iBooking", JOptionPane.INFORMATION_MESSAGE);
        } else {
            for (int i : tblUsuarios_UsuariosPanel.getSelectedRows()) {
                try {
                    dao.Eliminar((int) tblUsuarios_UsuariosPanel.getValueAt(i, 0));
                    model.removeRow(i);
                } catch (Exception e) {
                    System.out.println(e.getMessage());
                }
            }
        }
        //Recarga de datos en la tabla y la base de datos:
        //Metodo no necesitado para este accionamiento.
        //LoadUsers();
    }//GEN-LAST:event_btnBorrar_UsuariosPanelActionPerformed

    private void btnEditar_UsuariosPanelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditar_UsuariosPanelActionPerformed
        //CHECKPOINT: DDomingo 12/01/2025
        if (tblUsuarios_UsuariosPanel.getSelectedRow() > -1) {
            //NOTA: Las interacciones "DAO - Programming" simpre se recomienda usarlas con la condicional "try {...} catch (Exception e) {...}"
            try {
                int usuarioID = (int) tblUsuarios_UsuariosPanel.getValueAt(tblUsuarios_UsuariosPanel.getSelectedRow(), 0);
                DAOUsuarios dao = new DAOUsuariosImpl();
                View1.showJPanel(new AdicionesUsuarios(dao.getUsuarioByID(usuarioID)));
            } catch (Exception e) {
                System.out.println(e.getMessage());
            }
        } else {
            JOptionPane.showMessageDialog(null, "Debe seleccionar el usuario a editar", "iBooking", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_btnEditar_UsuariosPanelActionPerformed

    private void btnBuscar_UsuariosPanelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscar_UsuariosPanelActionPerformed
        try {
            //Instanciacion del valor de la busqueda:
            String usuarioBusqueda = txtBusqueda_UsuariosPanel.getText();
            //Validadcion para el campo de texto de busqueda:
            //NOTA: Metod reutilizado de otro panel, adaptado a este entorno
            if (usuarioBusqueda.isEmpty()) {
                JOptionPane.showMessageDialog(null, "Por favor, debe ingresar el nombre de usuario a buscar.", "iBooking", JOptionPane.WARNING_MESSAGE);
                //Redireccion el cursor al cuadro de texto "txtFldNombre_RegistroUsuarioPanel"
                txtBusqueda_UsuariosPanel.requestFocus();
                return;
            }
            //CHECKPOINT: Domingo 12/01/2025 - 11:14, corregir las leyendas de los txtgaps [CORREGIDO]
            //Comunicacion de Interface con Implement:
            DAOUsuarios dao = new DAOUsuariosImpl();
            //Instanciacion de la tabla a usar:
            DefaultTableModel model = (DefaultTableModel) tblUsuarios_UsuariosPanel.getModel();
            //Prueba en consola de la consulta "SELECT ....":
            //Limpieza de los valores de busqueda post consulta:
            model.setRowCount(0);
            //dao.Listar().forEach((u) -> System.out.println(u.getName()));
            dao.Listar(usuarioBusqueda).forEach((u) -> model.addRow(new Object[]{u.getId(), u.getName(), u.getLast_name_p(), u.getLast_name_m(),
                u.getDomicilio(), u.getTel()}));
        } catch (Exception e) {
            System.out.println(e.getMessage());
        }
    }//GEN-LAST:event_btnBuscar_UsuariosPanelActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBorrar_UsuariosPanel;
    private javax.swing.JButton btnBuscar_UsuariosPanel;
    private javax.swing.JButton btnEditar_UsuariosPanel;
    private javax.swing.JButton btnNuevo_UsuariosPanel;
    private javax.swing.JScrollPane jScrollPane1_UsuariosPanel;
    private javax.swing.JSeparator jSeparator1_UsuariosPanel;
    private javax.swing.JSeparator jSeparator2_UsuariosPanel;
    private javax.swing.JLabel lblTitle_UsuariosPanel;
    private javax.swing.JPanel pnlBackground_UsuariosPanel;
    private javax.swing.JTable tblUsuarios_UsuariosPanel;
    private javax.swing.JTextField txtBusqueda_UsuariosPanel;
    // End of variables declaration//GEN-END:variables
}
