/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

//CHECKPOINT: Lunes, 10/02/2025 - 
//NOTA: Analisis y optimizaacion de los paneles y funcionalidades.
import Views_panels.*;
import com.formdev.flatlaf.FlatLightLaf;
import java.awt.BorderLayout;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.util.Locale;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Fabrizio
 */
public class View1 extends javax.swing.JFrame {

    /**
     * Creates new form View1
     */
    public View1() {
        initComponents();
        //Instanciacion del metodo de estilos:
        InitStyles();
        //Llamado de metodo de localizacion inicial:
        this.setLocationRelativeTo(null);
        //Instanciacion de la fecha:
        setDate();
        //Inicializacion de los paneles informativos:
        InitContentPanel();
    }

    //Constructor almacen de estilos:
    private void InitStyles() {
        //Metodo de estilo de fuente (NOTA: Puede ser en comandos de HTML[h1,h2,...],
        //o puede ser en comando de medidas especificas: font:???px, fontStyle:???,...)
        lblTitleHeader1_MainPanel.putClientProperty("FlatLaf.styleClass", "h1");
        lblTitleHeader2_MainPanel.putClientProperty("FlatLaf.styleClass", "h1");
        lblTitleMenu_MainPanel.putClientProperty("FlatLaf.styleClass", "h1");
        lblTimeDateHeader1_MainPanel.putClientProperty("FlatLaf.styleClass", "h3");
        lblFraseHeader2_MainPanel.putClientProperty("FlatLaf.styleClass", "h2");
    }

    //Metodo de la fechad de hoy:
    private void setDate() {
        /*
        LocalDate now = LocalDate.now();
        int year = now.getYear();
        int day = now.getDayOfMonth();
        int month = now.getMonthValue();

        String[] meses = {"Enero", "Febrero", "Marzo", "Abril", "Mayo", "Junio",
            "Julio", "Agosto", "Setiembre", "Octubre", "Noviembre", "Diciembre"};
        time_date_label.setText("Fecha: " + day + " de " + meses[month - 1] + " del " + year);
         */
        //Metodo de DIA, FECHA mejorado
        LocalDate now = LocalDate.now();
        Locale spanishLocale = new Locale("es", "ES");
        lblTimeDateHeader1_MainPanel.setText(now.format(DateTimeFormatter.ofPattern("EEEE dd 'de' MMMM 'de ' YYYY", spanishLocale)));
    }

    //Panel informtivo 01: PRINCIPAL
    //NOTA: Medidas utilizadas para el caso, sujeto
    //a variacion.
    private void InitContentPanel() {
        //Metodo antiguo de ajuste:        
        //Usar: pnlContent.setLayout(new BorderLayout()); para el ajuste tipo FlowLayout
        pnlContent_MainPanel.setLayout(new BorderLayout());
        /*
        prinicipal pa1 = new prinicipal();
        pa1.setSize(800, 430);
        pa1.setLocation(0, 0);

        pnlContent.removeAll();
        pnlContent.add(pa1, BorderLayout.CENTER);
        pnlContent.revalidate();
        pnlContent.repaint();
         */

        //Nuevo metodo de inicializacion:
        showJPanel(new prinicipal());
    }

    //Metodo de ajuste del JPanel:    
    public static void showJPanel(JPanel p) {
        p.setSize(800, 430);
        p.setLocation(0, 0);

        pnlContent_MainPanel.removeAll();
        pnlContent_MainPanel.add(p, BorderLayout.CENTER);
        pnlContent_MainPanel.revalidate();
        pnlContent_MainPanel.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlBackground_MainPanel = new javax.swing.JPanel();
        pnlMenu_MainPanel = new javax.swing.JPanel();
        lblTitleMenu_MainPanel = new javax.swing.JLabel();
        jSeparator1Menu_MainPanel = new javax.swing.JSeparator();
        btnPrinicipalMenu_MainPanel = new javax.swing.JButton();
        btnPrestamosMenu_MainPanel = new javax.swing.JButton();
        btnDevolucionesMenu_MainPanel = new javax.swing.JButton();
        btnUsuariosMenu_MainPanel = new javax.swing.JButton();
        btnLibrosMenu_MainPanel = new javax.swing.JButton();
        btnReportesMenu_MainPanel = new javax.swing.JButton();
        btnSalirMenu_MainPanel = new javax.swing.JButton();
        pnlHeader1_MainPanel = new javax.swing.JPanel();
        lblTitleHeader1_MainPanel = new javax.swing.JLabel();
        lblTimeDateHeader1_MainPanel = new javax.swing.JLabel();
        pnlHeader2_MainPanel = new javax.swing.JPanel();
        lblTitleHeader2_MainPanel = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        lblFraseHeader2_MainPanel = new javax.swing.JLabel();
        pnlContent_MainPanel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1050, 660));

        pnlMenu_MainPanel.setBackground(new java.awt.Color(55, 57, 60));

        lblTitleMenu_MainPanel.setForeground(new java.awt.Color(255, 255, 255));
        lblTitleMenu_MainPanel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitleMenu_MainPanel.setText("iBooking");

        jSeparator1Menu_MainPanel.setBackground(new java.awt.Color(255, 255, 255));

        btnPrinicipalMenu_MainPanel.setBackground(new java.awt.Color(77, 80, 82));
        btnPrinicipalMenu_MainPanel.setForeground(new java.awt.Color(255, 255, 255));
        btnPrinicipalMenu_MainPanel.setIcon(new javax.swing.ImageIcon("C:\\Users\\Fabrizio\\OneDrive\\Documentos\\ToGit - NetBeans\\LibraryManagement_System\\Program_Images\\icons8-casa-30.png")); // NOI18N
        btnPrinicipalMenu_MainPanel.setText("PRINICIPAL");
        btnPrinicipalMenu_MainPanel.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 10, 1, 1, new java.awt.Color(0, 0, 0)));
        btnPrinicipalMenu_MainPanel.setBorderPainted(false);
        btnPrinicipalMenu_MainPanel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnPrinicipalMenu_MainPanel.setIconTextGap(10);
        btnPrinicipalMenu_MainPanel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrinicipalMenu_MainPanelActionPerformed(evt);
            }
        });

        btnPrestamosMenu_MainPanel.setBackground(new java.awt.Color(77, 80, 82));
        btnPrestamosMenu_MainPanel.setForeground(new java.awt.Color(255, 255, 255));
        btnPrestamosMenu_MainPanel.setIcon(new javax.swing.ImageIcon("C:\\Users\\Fabrizio\\OneDrive\\Documentos\\ToGit - NetBeans\\LibraryManagement_System\\Program_Images\\icons8-calendario-más-30.png")); // NOI18N
        btnPrestamosMenu_MainPanel.setText("PRESTAMOS");
        btnPrestamosMenu_MainPanel.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 10, 1, 1, new java.awt.Color(30, 33, 36)));
        btnPrestamosMenu_MainPanel.setBorderPainted(false);
        btnPrestamosMenu_MainPanel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnPrestamosMenu_MainPanel.setIconTextGap(10);
        btnPrestamosMenu_MainPanel.setMaximumSize(new java.awt.Dimension(60, 16));
        btnPrestamosMenu_MainPanel.setMinimumSize(new java.awt.Dimension(60, 16));
        btnPrestamosMenu_MainPanel.setPreferredSize(new java.awt.Dimension(60, 16));
        btnPrestamosMenu_MainPanel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrestamosMenu_MainPanelActionPerformed(evt);
            }
        });

        btnDevolucionesMenu_MainPanel.setBackground(new java.awt.Color(77, 80, 82));
        btnDevolucionesMenu_MainPanel.setForeground(new java.awt.Color(255, 255, 255));
        btnDevolucionesMenu_MainPanel.setIcon(new javax.swing.ImageIcon("C:\\Users\\Fabrizio\\OneDrive\\Documentos\\ToGit - NetBeans\\LibraryManagement_System\\Program_Images\\icons8-hoy-30.png")); // NOI18N
        btnDevolucionesMenu_MainPanel.setText("DEVOLUCIONES");
        btnDevolucionesMenu_MainPanel.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 10, 1, 1, new java.awt.Color(30, 33, 36)));
        btnDevolucionesMenu_MainPanel.setBorderPainted(false);
        btnDevolucionesMenu_MainPanel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnDevolucionesMenu_MainPanel.setMaximumSize(new java.awt.Dimension(60, 16));
        btnDevolucionesMenu_MainPanel.setMinimumSize(new java.awt.Dimension(60, 16));
        btnDevolucionesMenu_MainPanel.setPreferredSize(new java.awt.Dimension(60, 16));
        btnDevolucionesMenu_MainPanel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDevolucionesMenu_MainPanelActionPerformed(evt);
            }
        });

        btnUsuariosMenu_MainPanel.setBackground(new java.awt.Color(77, 80, 82));
        btnUsuariosMenu_MainPanel.setForeground(new java.awt.Color(255, 255, 255));
        btnUsuariosMenu_MainPanel.setIcon(new javax.swing.ImageIcon("C:\\Users\\Fabrizio\\OneDrive\\Documentos\\ToGit - NetBeans\\LibraryManagement_System\\Program_Images\\icons8-grupo-de-primer-plano-seleccionado-30.png")); // NOI18N
        btnUsuariosMenu_MainPanel.setText("USUARIOS");
        btnUsuariosMenu_MainPanel.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 10, 1, 1, new java.awt.Color(30, 33, 36)));
        btnUsuariosMenu_MainPanel.setBorderPainted(false);
        btnUsuariosMenu_MainPanel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnUsuariosMenu_MainPanel.setMaximumSize(new java.awt.Dimension(60, 16));
        btnUsuariosMenu_MainPanel.setMinimumSize(new java.awt.Dimension(60, 16));
        btnUsuariosMenu_MainPanel.setPreferredSize(new java.awt.Dimension(60, 16));
        btnUsuariosMenu_MainPanel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUsuariosMenu_MainPanelActionPerformed(evt);
            }
        });

        btnLibrosMenu_MainPanel.setBackground(new java.awt.Color(77, 80, 82));
        btnLibrosMenu_MainPanel.setForeground(new java.awt.Color(255, 255, 255));
        btnLibrosMenu_MainPanel.setIcon(new javax.swing.ImageIcon("C:\\Users\\Fabrizio\\OneDrive\\Documentos\\ToGit - NetBeans\\LibraryManagement_System\\Program_Images\\icons8-libros-30.png")); // NOI18N
        btnLibrosMenu_MainPanel.setText("LIBROS");
        btnLibrosMenu_MainPanel.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 10, 1, 1, new java.awt.Color(30, 33, 36)));
        btnLibrosMenu_MainPanel.setBorderPainted(false);
        btnLibrosMenu_MainPanel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnLibrosMenu_MainPanel.setMaximumSize(new java.awt.Dimension(60, 16));
        btnLibrosMenu_MainPanel.setMinimumSize(new java.awt.Dimension(60, 16));
        btnLibrosMenu_MainPanel.setPreferredSize(new java.awt.Dimension(60, 16));
        btnLibrosMenu_MainPanel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLibrosMenu_MainPanelActionPerformed(evt);
            }
        });

        btnReportesMenu_MainPanel.setBackground(new java.awt.Color(77, 80, 82));
        btnReportesMenu_MainPanel.setForeground(new java.awt.Color(255, 255, 255));
        btnReportesMenu_MainPanel.setIcon(new javax.swing.ImageIcon("C:\\Users\\Fabrizio\\OneDrive\\Documentos\\ToGit - NetBeans\\LibraryManagement_System\\Program_Images\\icons8-informe-gráfico-30.png")); // NOI18N
        btnReportesMenu_MainPanel.setText("REPORTES");
        btnReportesMenu_MainPanel.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 10, 1, 1, new java.awt.Color(30, 33, 36)));
        btnReportesMenu_MainPanel.setBorderPainted(false);
        btnReportesMenu_MainPanel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnReportesMenu_MainPanel.setMaximumSize(new java.awt.Dimension(60, 16));
        btnReportesMenu_MainPanel.setMinimumSize(new java.awt.Dimension(60, 16));
        btnReportesMenu_MainPanel.setPreferredSize(new java.awt.Dimension(60, 16));
        btnReportesMenu_MainPanel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReportesMenu_MainPanelActionPerformed(evt);
            }
        });

        btnSalirMenu_MainPanel.setBackground(new java.awt.Color(77, 80, 82));
        btnSalirMenu_MainPanel.setForeground(new java.awt.Color(255, 255, 255));
        btnSalirMenu_MainPanel.setIcon(new javax.swing.ImageIcon("C:\\Users\\Fabrizio\\OneDrive\\Documentos\\ToGit - NetBeans\\LibraryManagement_System\\Program_Images\\icons8-exportar-30.png")); // NOI18N
        btnSalirMenu_MainPanel.setText("SALIR");
        btnSalirMenu_MainPanel.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 10, 1, 1, new java.awt.Color(77, 80, 82)));
        btnSalirMenu_MainPanel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnSalirMenu_MainPanel.setIconTextGap(10);
        btnSalirMenu_MainPanel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirMenu_MainPanelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlMenu_MainPanelLayout = new javax.swing.GroupLayout(pnlMenu_MainPanel);
        pnlMenu_MainPanel.setLayout(pnlMenu_MainPanelLayout);
        pnlMenu_MainPanelLayout.setHorizontalGroup(
            pnlMenu_MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMenu_MainPanelLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(lblTitleMenu_MainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(pnlMenu_MainPanelLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jSeparator1Menu_MainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(btnPrinicipalMenu_MainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(btnPrestamosMenu_MainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(btnDevolucionesMenu_MainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(btnUsuariosMenu_MainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(btnLibrosMenu_MainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(btnReportesMenu_MainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(btnSalirMenu_MainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        pnlMenu_MainPanelLayout.setVerticalGroup(
            pnlMenu_MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMenu_MainPanelLayout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(lblTitleMenu_MainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(jSeparator1Menu_MainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(btnPrinicipalMenu_MainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(btnPrestamosMenu_MainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(btnDevolucionesMenu_MainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(btnUsuariosMenu_MainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(btnLibrosMenu_MainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(btnReportesMenu_MainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 200, Short.MAX_VALUE)
                .addComponent(btnSalirMenu_MainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pnlHeader1_MainPanel.setBackground(new java.awt.Color(55, 57, 60));

        lblTitleHeader1_MainPanel.setForeground(new java.awt.Color(255, 255, 255));
        lblTitleHeader1_MainPanel.setText("Read the world!");

        lblTimeDateHeader1_MainPanel.setForeground(new java.awt.Color(255, 255, 255));
        lblTimeDateHeader1_MainPanel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblTimeDateHeader1_MainPanel.setText("{dayname} {day} de {month} del {year}");

        javax.swing.GroupLayout pnlHeader1_MainPanelLayout = new javax.swing.GroupLayout(pnlHeader1_MainPanel);
        pnlHeader1_MainPanel.setLayout(pnlHeader1_MainPanelLayout);
        pnlHeader1_MainPanelLayout.setHorizontalGroup(
            pnlHeader1_MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlHeader1_MainPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitleHeader1_MainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblTimeDateHeader1_MainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        pnlHeader1_MainPanelLayout.setVerticalGroup(
            pnlHeader1_MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlHeader1_MainPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlHeader1_MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTitleHeader1_MainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTimeDateHeader1_MainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(12, Short.MAX_VALUE))
        );

        pnlHeader2_MainPanel.setBackground(new java.awt.Color(153, 153, 153));

        lblTitleHeader2_MainPanel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblTitleHeader2_MainPanel.setText("CENTRO DE CONTROL DE LA BIBLIOTECA:");

        lblFraseHeader2_MainPanel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblFraseHeader2_MainPanel.setText("\"Todo aquel que lee, deja en cajon de sus recuerdos una ánecdota mas para su existir\"");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblFraseHeader2_MainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblFraseHeader2_MainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout pnlHeader2_MainPanelLayout = new javax.swing.GroupLayout(pnlHeader2_MainPanel);
        pnlHeader2_MainPanel.setLayout(pnlHeader2_MainPanelLayout);
        pnlHeader2_MainPanelLayout.setHorizontalGroup(
            pnlHeader2_MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlHeader2_MainPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlHeader2_MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(pnlHeader2_MainPanelLayout.createSequentialGroup()
                        .addComponent(lblTitleHeader2_MainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 560, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 258, Short.MAX_VALUE)))
                .addContainerGap())
        );
        pnlHeader2_MainPanelLayout.setVerticalGroup(
            pnlHeader2_MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlHeader2_MainPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitleHeader2_MainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pnlContent_MainPanel.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout pnlContent_MainPanelLayout = new javax.swing.GroupLayout(pnlContent_MainPanel);
        pnlContent_MainPanel.setLayout(pnlContent_MainPanelLayout);
        pnlContent_MainPanelLayout.setHorizontalGroup(
            pnlContent_MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 830, Short.MAX_VALUE)
        );
        pnlContent_MainPanelLayout.setVerticalGroup(
            pnlContent_MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 450, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout pnlBackground_MainPanelLayout = new javax.swing.GroupLayout(pnlBackground_MainPanel);
        pnlBackground_MainPanel.setLayout(pnlBackground_MainPanelLayout);
        pnlBackground_MainPanelLayout.setHorizontalGroup(
            pnlBackground_MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBackground_MainPanelLayout.createSequentialGroup()
                .addComponent(pnlMenu_MainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(pnlBackground_MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlHeader1_MainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlContent_MainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlHeader2_MainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        pnlBackground_MainPanelLayout.setVerticalGroup(
            pnlBackground_MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlMenu_MainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(pnlBackground_MainPanelLayout.createSequentialGroup()
                .addComponent(pnlHeader1_MainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(150, 150, 150)
                .addComponent(pnlContent_MainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(pnlBackground_MainPanelLayout.createSequentialGroup()
                .addGap(68, 68, 68)
                .addComponent(pnlHeader2_MainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlBackground_MainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlBackground_MainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalirMenu_MainPanelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirMenu_MainPanelActionPerformed
        //Here 01/01/25
        int response = JOptionPane.showConfirmDialog(null, "¿Esta seguro que desea salir?", "iBooking", JOptionPane.YES_NO_OPTION, JOptionPane.WARNING_MESSAGE);
        if (response == JOptionPane.YES_OPTION) {
            System.exit(0);
        } else {
            //NOthng to code here.
        }
    }//GEN-LAST:event_btnSalirMenu_MainPanelActionPerformed

    //Llamado de cada panel segun su boton asignado:
    private void btnPrinicipalMenu_MainPanelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrinicipalMenu_MainPanelActionPerformed
        showJPanel(new prinicipal());
    }//GEN-LAST:event_btnPrinicipalMenu_MainPanelActionPerformed

    private void btnPrestamosMenu_MainPanelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrestamosMenu_MainPanelActionPerformed
        showJPanel(new Prestamos());
    }//GEN-LAST:event_btnPrestamosMenu_MainPanelActionPerformed

    private void btnDevolucionesMenu_MainPanelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDevolucionesMenu_MainPanelActionPerformed
        showJPanel(new Devoluciones());
    }//GEN-LAST:event_btnDevolucionesMenu_MainPanelActionPerformed

    private void btnUsuariosMenu_MainPanelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUsuariosMenu_MainPanelActionPerformed
        showJPanel(new Usuarios());
    }//GEN-LAST:event_btnUsuariosMenu_MainPanelActionPerformed

    private void btnLibrosMenu_MainPanelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLibrosMenu_MainPanelActionPerformed
        showJPanel(new Libros());
    }//GEN-LAST:event_btnLibrosMenu_MainPanelActionPerformed

    private void btnReportesMenu_MainPanelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReportesMenu_MainPanelActionPerformed
        showJPanel(new Reportes());
    }//GEN-LAST:event_btnReportesMenu_MainPanelActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        FlatLightLaf.setup();

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new View1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDevolucionesMenu_MainPanel;
    private javax.swing.JButton btnLibrosMenu_MainPanel;
    private javax.swing.JButton btnPrestamosMenu_MainPanel;
    private javax.swing.JButton btnPrinicipalMenu_MainPanel;
    private javax.swing.JButton btnReportesMenu_MainPanel;
    private javax.swing.JButton btnSalirMenu_MainPanel;
    private javax.swing.JButton btnUsuariosMenu_MainPanel;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1Menu_MainPanel;
    private javax.swing.JLabel lblFraseHeader2_MainPanel;
    private javax.swing.JLabel lblTimeDateHeader1_MainPanel;
    private javax.swing.JLabel lblTitleHeader1_MainPanel;
    private javax.swing.JLabel lblTitleHeader2_MainPanel;
    private javax.swing.JLabel lblTitleMenu_MainPanel;
    private javax.swing.JPanel pnlBackground_MainPanel;
    private static javax.swing.JPanel pnlContent_MainPanel;
    private javax.swing.JPanel pnlHeader1_MainPanel;
    private javax.swing.JPanel pnlHeader2_MainPanel;
    private javax.swing.JPanel pnlMenu_MainPanel;
    // End of variables declaration//GEN-END:variables
}
